### ISSUE TITLE
Custom styling via CSS

### ISSUE THREAD

**Issue by Eflores89** [inukshuk/jekyll-scholar#105]
I'm not sure if this is a feature request, or i'm missing something from the setup. 

I have the following files in corresponding folders: `bibliography.bib `, `bibliography.html`, `bibliography.css`.

When writing posts i'm calling: 

`{% reference foo %}`

And I get the desired output, but i'm trying to find a way to style the references via css. I would think that the point of `bibliography.css` is just that, but it doesn't seem to be the case. 

While inspecting the generated html I see a `id = foo` tag, which of course I don't have in css, and thus it is inheriting the properties from the `post.css`.

I'm aware of this post:  https://github.com/inukshuk/jekyll-scholar/issues/68 but it doesn't answer my question because i'm not trying to change the CSL, only how it is displayed (size, color, etc). 

Of course I could edit the resulting html and place a tag, but this would be absolutely insane for 500+ posts!

What would be the correct/easiest way to style dynamically the references? 

**disclosure: my level of expertise in ruby is close to nil**

**Comment by inukshuk** [comment]
I'm afraid I don't quite understand what you're trying to do. There are many ways to apply your custom CSS to the references; the id is there precisely to allow you to style individual items (if you know their id obviously), but you can also just adjust the reference template to set a class or something like that to make it easy to select the references in your CSS.

**Comment by Eflores89** [comment]
I want exactly this: 

> but you can also just adjust the reference template to set a class

Via the html? Do you have a quick example?

**Comment by inukshuk** [comment]
See [here](https://github.com/inukshuk/jekyll-scholar#bibliography-template)

For example, something like `<span class="reference">{{reference}}</span>`.
