### ISSUE TITLE
--query @*[author=Name] only work on the first author

### ISSUE THREAD

**Issue by SteveViss** [inukshuk/jekyll-scholar#106]
Hi @inukshuk,

When I run this query ``` {% bibliography --query @*[author ^= {{ member.LastName }}] %} ```, I only get all publications where ``` member.LastName ``` is the first author. Any idea how to query on the entire string of authors ?

Really nice work !

**Comment by inukshuk** [comment]
Hi @SteveViss, liquid interpolation inside queries: that looks like a pretty cool use case you have there!

For more about queries, [check out the bibtex-ruby readme](https://github.com/inukshuk/bibtex-ruby#queries). Basically, `^=` matches only at the beginning of a field; you should probably use `~=` instead.

**Comment by SteveViss** [comment]
Thanks @inukshuk. Working perfectly !
