### ISSUE TITLE
Prevent line breaks in et al.

### ISSUE THREAD

**Issue by reitzig** [inukshuk/jekyll-scholar#107]
Currently, "et al." in citations can be broken.

Fix: use `&nbsp;` (or `&#8239;` for a thinner non-breaking space).

**Comment by inukshuk** [comment]
The terms used by the citations come from a CSL locale file; you can set the locale using the `locale` option (it defaults to 'en-US'). You could copy the default locale from `$(bundle show csl-styles)/vendor/locales` and adjust the terms. This should support unicode, too, so no need for code numbers.

**Comment by reitzig** [comment]
Ah, that's where they come from! Thanks.

So if I wanted to report this as a bug, I'd have to head over to citation-style-language/locales, correct?

**Comment by inukshuk** [comment]
Exactly. You may want to check with @rmzelle and @adam3smith first, though, if there is a policy in place for handling special whitespace.

**Comment by adam3smith** [comment]
we'd want to see documentation that the space _shoud_ be non-breaking for any given language or at least style. et al are two words, I don't think it's obvious that a line break between them is wrong.

**Comment by reitzig** [comment]
@adam3smith I am not able to find *any* recommendation on how to typeset "et al.". It's certainly two words, technically, but they also form an abbreviation *together*. For instances, you'd do `B.\,Sc.\ ` for the academic grade; note the thin, non-breaking space in between. To my knowledge, it's preferred to deal with `i.\,e.\ ` and `e.\,g.\ ` (and others) similarly. 

I guess that's why I consider `et\,al.\ ` to be the right way, even though "et" is not abbreviated itself.

**Comment by rmzelle** [comment]
Yeah, like @adam3smith said, we would only change the CSL locale files if we found documentation suggesting that this is generally required/desired. In the meantime, you're of course free to redefine these terms with the preferred white-space within your CSL style.
