### ISSUE TITLE
Can we use dependent styles? How?

### ISSUE THREAD

**Issue by reitzig** [inukshuk/jekyll-scholar#108]
I have tried several styles from the `dependent` folder from the [CSL respository](https://github.com/citation-style-language/styles/). I could not get any one of them to work.

I have tried configuration lines of the form

```
  style: bit-numerical-mathematics
  style: bit-numerical-mathematics.csl
  style: bitnumericalmathematics
  style: bit-numerical-mathematics.csl
  style: "BIT Numerical Mathematics"
  style: "dependent/bit-numerical-mathematics.csl"
  style: dependent/bit-numerical-mathematics.csl
  style: "https://github.com/citation-style-language/styles/blob/cac22204fe6300c0e3a6c603673e122b09f07172/dependent/bit-numerical-mathematics.csl"
```

and probably some more.

Is there a trick to this?

**Comment by inukshuk** [comment]
Ah, yes, jekyll-scholar does not handle dependent styles yet. This would be really easy to implement though. If I am not mistaken, we'd just have to add a few lines [here](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L8):

     style = CSL::Style.load k
     style = style.independent_parent unless style.independent?
     h[k.to_s] = style

If I add this real quick could you test if it works?

**Comment by inukshuk** [comment]
I pushed this to master, if you want to try it out.

**Comment by reitzig** [comment]
Thanks, but I'll stick to the gem version and try again when the update hits there. :)

Looking at the code, are you sure that the changes from the dependent style file are honored? Looks to me as if you just use the parent style. Well, [not much can change](http://docs.citationstyles.org/en/latest/specification.html#dependent-styles) but locales are mentioned explicitly. `category` tags appear in dependent styles as well, but I don't know if they are allowed to differ from the parent style.

**Comment by inukshuk** [comment]
You're right, we ought to copy any locales if they are present, thanks for catching that!

By the way, I'm not planning on making a Jekyll 2 releases anymore; therefore, the next release will be held back until Jekyll 3 is ready.

**Comment by reitzig** [comment]
Okay, let's hope it'll arrive soon, then!
(And not break everything I've been tinkering together these past weeks... X) )

**Comment by reitzig** [comment]
Do you still need some kind of confirmation? I'm on jekyll-scholar 5.1.0 now so I could probably run a quick test.

**Comment by inukshuk** [comment]
If you can confirm that this works for you, we can close this. I have not added anything regarding locales yet, but I did check and there is no official dependent style that seems to use this feature so this isn't really high priority. Thanks!

**Comment by reitzig** [comment]
I can confirm that

    style: dependent/bit-numerical-mathematics

works as intended (also with added `.csl`) now. Thanks!

I think a point can be made that jekyll-scholar should look in `dependent` (and other directories, if any) if it does not find the specified style in the main directory, but that's a minor issue. In any case, you may want to update the documentation; it currently says

> You can use any style that ships with CiteProc-Ruby by name

which is not entirely true here; you need the path prefix.

**Comment by inukshuk** [comment]
Cool, thanks for the follow-up!
