### ISSUE TITLE
How do I query by type?

### ISSUE THREAD

**Issue by kristiannordestgaard** [inukshuk/jekyll-scholar#110]
I tried `{% bibliography --query @*[type=interview] %}` but no luck. How is this done properly?

**Comment by inukshuk** [comment]
Check out the bibtex-ruby [readme](https://github.com/inukshuk/bibtex-ruby#queries).

You can do something like `@interview`, `@*` queries for all types.

**Comment by kristiannordestgaard** [comment]
Sorry, I was being unclear. A relevant entry could look like this: 

@article{hollis1979,
    author = {Hollis, Richard},
    title = {TV Zone},
    journal = {Starburst},
    year = {1983},
    issue = {58},
    pages = {40},
    **type = {interview},**
}

That is what I meant by "type."

**Comment by sgroth** [comment]
@article{hollis1979,
…
interview = {true}
}

works in combination with {% bibliography --query @*[interview^=true] %}.

**Comment by kristiannordestgaard** [comment]
That is not proper BibTeX, though?

**Comment by inukshuk** [comment]
@kristiannordestgaard this is probably a bug in bibtex-ruby. we'll have to fix it there.

**Comment by kristiannordestgaard** [comment]
Great, let me know what happens. I'll stay subscribed to this issue. 

By the way, @inukshuk, have a look [here](http://kristian.anapnea.net/quatermass/about/) :)

**Comment by inukshuk** [comment]
@kristiannordestgaard cheers :)

Anyway, this was an old bug: https://github.com/inukshuk/bibtex-ruby/issues/104

I pushed a work around for this (i.e., it works in bibtex-ruby 4.0.15) but ideally someone should replace all occurrences of `type` in bibtex-ruby with `bibtex_type` or something like that. Tedious work, so no one has got around to doing it.
