### ISSUE TITLE
Question about Sorting by Year

### ISSUE THREAD

**Issue by olafland** [inukshuk/jekyll-scholar#111]
I really like this plug-in. On my page I am sorting my publications by year, something similar to:

```
{% assign y = 'now' | date: "%Y" %}
{% for i in (2003..{{y}}) reversed %}
#### {{i}}
{% bibliography --query @*[year={{i}}] %}
{% endfor %}
```
What would be nice, is to query whether publications for a particular year exist. I tried a couple of things, but nothing worked for me (maybe just because Liquid and I still have to become good friends). I had something like this in mind:

```
{% assign y = 'now' | date: "%Y" %}
{% for i in (2003..{{y}}) reversed %}
{% if bibliography --query @*[year={{i}}] != blank %}
#### {{i}}
{% bibliography --query @*[year={{i}}] %}
{% endif %}
{% endfor %}
```

But, as I said,  I could not get it to work this way. Any hints on how to check whether publications for a particular year exist?

**Comment by inukshuk** [comment]
The Bibliography doesn't work like that, I'm afraid. The querying itself is easy, but you would have to add a custom liquid tag to achieve this I believe.

**Comment by olafland** [comment]
Ok, I see. Thanks for your quick reply.
