### ISSUE TITLE
Change {{entry.author}} output to forename lastname

### ISSUE THREAD

**Issue by jbreitbart** [inukshuk/jekyll-scholar#112]
I am using a template to generate my publication list. The code in my template looks something like

```<h4 class="resume-item-details">{{entry.author}} &bull; {{entry.year}}</h4>```

entry.author always returns lastname, forname. Is there a way to change that to forename lastername?

**Comment by inukshuk** [comment]
If you upgrade to 5.1.0 you can do something like: `{{entry.author_0_last}}` to print the last name. This sort of thing works for all name fields (author, editor, translator). You need to know the index of the name (e.g., `author_0` is the first author, `author_1` the second, etc.). The available name parts are: last, first, prefix, suffix.

Happy hacking!
