### ISSUE TITLE
Detail pages moved to folders?

### ISSUE THREAD

**Issue by sgroth** [inukshuk/jekyll-scholar#113]
Just noticed this: the detail pages have been moved from /bibliography/citeykey.html to /bibliography/citekey/index.html – as a consequence, the links to the detail pages are broken as they still point to the old location.

Is there a way to manually reconfigure this?

Running jekyll 3.0.0 and jekyll-scholar 5.1.0

**Comment by inukshuk** [comment]
Did you see #55 and #103 -- this behaviour is dependent on the permalink style.

Since this has changed so many times, it would be great if you could provide a failing test case if there is still an issue.

**Comment by sgroth** [comment]
Sorry, I missed #55 and #103 – setting the permalink to "pretty" works (FYI, I had it set to /:year/:month/:day/:title/ before which worked fine up until the 3.0.0 version).

Thanks! Great plugin!
