### ISSUE TITLE
Add custom text between groups of references in a publication list

### ISSUE THREAD

**Issue by raphaelfournier** [inukshuk/jekyll-scholar#114]
I would like, as @hpatel wanted to accomplish in the very long #1 entry, to obtain a list of publications grouped by (say) years or publication type ("journal", "conferences", "phd", etc.) with text between the groups (typically a "header" to indicate the "name" for the group). 

For publication types, since there are only a few, it can be done manually with something like:

     ## Conferences
    `bibliography --query @conference`
     
     ## Journal
    `bibliography --query @article`

However, for grouping by "years" (or years and month), it could be tedious. Apparently, @hpatel managed to obtain something in jekyll-scholar-extras for this (exchange with @inukshuk on May, 4 2012). However, jekyll-scholar-extras' template seems broken with current jekyll version (3.0.1). I carefully read the #1 entry but I could not find the appropriate code/template. Moreover, I saw that some functionalities from jekyll-scholar-extras have been incorporated in jekyll-scholar, but I know too few ruby or the internals of jekyll-scholar to understand if and where this feature has been incorporated. 

Ideally, one could customize the text between groups (say "journal articles" for @article entries, or "Year 2015").

Some jekyll-scholar-extras code can be probably reused here, like the `lib/jekyll/scholar/extras/bibliography_bytype.rb` and `lib/jekyll/scholar/extras/bibliography_hdp.rb`, but I don't know exactly how to:
- incorporate them in my current working jekyll website (I guess I should put those files in my `_plugins` directory)
- select the proper one in my markdown code

By the way, thank you very much @inukshuk for the amazing work you've done here!

P.S.: Setup: Jekyll 3.0.1 on Archlinux. Working with a one-file list of publications containing references, such as one that could be exported from JabRef or a similar software.

**Comment by inukshuk** [comment]
You want to group your publication by year, is that it? If so, I think #25 will be relevant discussion but it looks like this has not been implemented yet.

Having said that, you can probably achieve this now much easier than back then using the liquid template. If you can set up an initial template I can probably help you get it to work. Basically, you need something like this in your template:

    {% for year in (1980..2020) %}
      <h1>{{ year }}</h1>
      <% bibliography --query @*[year = {{year}}] %}
    {% endfor %}

I haven't tested this but it should work along those lines. Now all we need is an if condition that checks if the bibliography satisfies a given condition so that you don't print years for which there are no entries. If we add this I think we actually have a pretty easy solution for arbitrary grouped publication lists which we should add to the readme.

**Comment by raphaelfournier** [comment]
Well, thank you for your quick and complete reply!

You're right, #25 is relevant and provide adequate code for grouping by year. But, since jekyll-scholar-extras is out-of-date, I'm not sure how one could use it.

Though, your solution using the liquid template works, thank you! A condition to avoid printing empty years would be great also, yes! For reference, I'm working on http://raphael.fournier-sniehotta.fr/research/publications.html.

Two other but related issues on the topic (let me know if I should open separate "Issues"): 

* Would it be possible to add custom classes (or attributes) to the `<ol>` for each "group"? Currently, I have seen that there's "bibliography_list_tag" (defaults to ol) and "bibliography_item_tag" (defaults to li), but it's global. I think it could be great to output something along the lines of `<ol class="conferences" reversed>`
(I hacked something similar with an inside `<div>` for the class, with javascript for the reversed attribute).

* Would it be possible to know the number of entries per group or for the whole bibliography? So, that, for a given group or the whole publications list, we can output somewhere: "N publications in year {{ year }}, with #j journals and #k conferences"

Thanks!

**Comment by kaytwo** [comment]
HI @raphaelfournier,
I just ran into this issue too. I solved the "avoid printing empty years" issue with a bit of a dirty hack - an empty year prints out 30 characters for me, so I added some wiggle room and wrote this:

```liquid
{% for year in (2000..2030) reversed %}  
  {% capture bib_entries %}{% bibliography --query @*[year = {{year}}] %}{% endcapture %}
  {% if  bib_entries.size > 90  %}
  <h2> {{ year }} </h2>
  {{ bib_entries }}
  {% endif %}
{% endfor %}
```

I don't have much to add for your other issues though, good luck with those. Cheers!

**Comment by raphaelfournier** [comment]
Oh, that's somewhat dirty but should work for me too, thanks! 
I had not realized the power of "capture", I should be able to hack something with it for my second point (a summary of a year or of all years).

**Comment by inukshuk** [comment]
Grouping support was added in #127

**Comment by Lisa-Monique** [comment]
Now that grouping is supported how can I add custom classes to groups or text between groups?
