### ISSUE TITLE
How to override defaults

### ISSUE THREAD

**Issue by rsm5139** [inukshuk/jekyll-scholar#115]
Hi, I'm having trouble setting the defaults for the configuration. I copy/pasted the example defaults from the README file, changed some value, but nothing happens. Can I get an example of exactly what to put in my _config.yml file?

Also, how do I link to other styles, just include the url to the raw csl file?

**Comment by inukshuk** [comment]
All standard CSL styles should be included, so it is sufficient to use their name; but you can also use a full path or URL to the style.

As far as the config is concerned, the example in the readme is just that: you should be able to just copy it into your _config.yml file.
