### ISSUE TITLE
Optional link in template

### ISSUE THREAD

**Issue by cdetroye** [inukshuk/jekyll-scholar#116]
Hi,

I have *some* references that have a pdf in my repository directory, but most of them don't. The thing is that the template in my configuration (shown below) generates the `<a/>` anyway. Is there a fix possible to make it only generate the html if there is in fact a `links.pdf`?

```
scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending
  repository: 'repository'
  source: '_bibliography'
  bibliography: bibliography.bib
  bibliography_template: <abbr>[{{key}}]</abbr>{{reference}} <a class="pdficon" href="{{links.pdf}}">PDF</a>

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
```

My temporary solution is to traverse the DOM afterwards and remove empty links.

**Comment by inukshuk** [comment]
You can use Liquid conditionals in your template, that should do the trick, no?
