### ISSUE TITLE
Double braces in bibtex are executed as Liquid expression

### ISSUE THREAD

**Issue by JoostvanPinxten** [inukshuk/jekyll-scholar#117]
I had some entries with double curly braces in Scholar. Typical usage of such extra curly braces arer due to acronyms in the paper titles and/or books that need to maintain the proper capitalization.

E.g., entries such as:

```
@book{some-book-name,
    title={{site.time}}
}
```
leads to```entry.title= "site.time"```(which is what I expected), but also leads to: ```entry.bibtex``` to contain the current time as the title.

So it seems that double curly braces get evaluated and will not output the literal "site.time" in the page.entry.bibtex. It will instead be rendered through Liquid.

One way around this is to use raw mode as follows: ```{%raw%}{{page.entry.bibtex}}{%endraw%}```, however, this seems like an 'undocumented feature', and I would like to know if this difference is by design, or should be considered a bug?

**Comment by inukshuk** [comment]
Good catch!

Unfortunately I think using the `raw` tag is probably the best solution here. You can search the issues for context, but  iirc we make a point of not applying filters when assigning the bibtex property (specifically, the latex filter would remove the braces, which is what happens to `entry.title` in your example).

We could wrap the entire bibtex content with a raw tag by default, but then users who expect liquid tags to be evaluated would probably report this as an error.

**Comment by JoostvanPinxten** [comment]
Hmm, yes, I was afraid of that. Although I could not come up with a well-reasoned usecase for using liquid-tags inside the bibtex entries though... It took me quite a while before I understood that they are processed as Liquid tags.

Is it maybe an option to create a configuration option in Scholar to use 'raw' entries vs the 'normal' entries?

**Comment by inukshuk** [comment]
If wrapping the entry in a raw tag by default works as expected, we could introduce a new configuration option to enable/disable this behaviour.

Do you want to try it out?

We fetch the data [here](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L313) -- `bibtex_skip_fields` lets you define fields which should not be included (e.g. abstracts) that's why there are two branches there. Basically, once `e['bibtex']` has been set, you could simply wrap it with a raw tag. If that works, we could add a configuration option and a test case.

**Comment by JoostvanPinxten** [comment]
Thanks for pointing me to that location. 

Using ```e['bibtex'] = '{%raw%}' + entry.to_s + '{%endraw%}'``` yields the same results as adding them manually (in my custom details_page html). I suppose that this needs to be done [here](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L322) too? Are there any other cases that I may have missed?

**Comment by inukshuk** [comment]
I think that should be it; actually, I would wrap the contents after line 323 -- that way you only need to do it once (and it is easier to understand if we test for the configuration option there).

**Comment by JoostvanPinxten** [comment]
That sounds like a good plan,

Btw; thanks for considering this as a configuration option for this kind of usage, and for replying so fast and accurately :-)

**Comment by inukshuk** [comment]
I added a `-R` / `--raw_bibtex` option for this.

**Comment by inukshuk** [comment]
Thanks for contributing!

**Comment by JoostvanPinxten** [comment]
Thanks for this first step. However, it does not actually fix the issue on the details page. I've forked the repository now and will try to make a failing test + a fix for the cite_details page. I don't think we can avoid adding a global configuration tag for that, as you can't pass such flags to the generated pages in another way?.

**Comment by inukshuk** [comment]
You're right. If you add a configuration option instead, feel free to remove the per-tag flag I added above.
