### ISSUE TITLE
No access to site-global settings in bibliography layout

### ISSUE THREAD

**Issue by JoostvanPinxten** [inukshuk/jekyll-scholar#118]
The ```site``` global variables/config that I'm used to having in a Jekyll layout, is not accessible in the rendering of references. As I'm currently in the process of making a template that will be used in different contexts, I would like to keep the settings for e.g. images global.

For example, with these ```config.yml``` settings, the output of a reference is the empty string:

``` 
scholar:
      bibliography_template: "{{site.time}}"
```

Is it possible to provide access to this global variable, or is it disabled for a particular reason? It seems that the [site attribute is available](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/generators/details.rb#L8), but cannot be used somehow in the template.

**Comment by inukshuk** [comment]
You can expose additional variables [here](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L292) -- I'm not entirely sure `site` (it is available in that context) is the same that jekyll normally exposes (though it probably is).

**Comment by JoostvanPinxten** [comment]
I have not been able to retrieve the right liquified version of the site object. I've noticed that the recommended way to instantiate a renderer is to ask the site to create a liquid renderer (as is shown in the Jekyll source code).

I ran into a problem that is tricky for me to debug; I can now use the site data, and also use the entry, but i cannot use the 'merge' method that was used before. Nor ref.merge(payload) nor payload.merge(ref) works for me, although `.class` calls on either return `Hash`...

So the current version (below) instantiates a Liquid template via Jekyll (not 100% sure if that is necessary), and appends the reference information to the payload.
``` ruby
      def liquid_template
        return @liquid_template if @liquid_template

        tmp = bibliography_template

        case
        when tmp.nil?, tmp.empty?
          tmp = '{{reference}}'
        when site.layouts.key?(tmp)
          tmp = site.layouts[tmp].content
        end

        @liquid_template = site.liquid_renderer.file("Scholar::bibliography_template").parse(tmp)
      end

      def bibliography_tag(entry, index)
        return missing_reference unless entry
		payload = site.site_payload
		ref = reference_data(entry, index)

		payload.reject!{|k| k == 'ref'}
		# payload.merge(ref) # this doesn't seem to work as I intend it to do
		# the payload contains an empty string for the 'entry' key

		payload['entry'] = ref['entry']
		payload['reference'] = ref['reference']
		payload['key'] = ref['key']
		payload['type'] = ref['type']
		payload['link'] = ref['link']
		payload['links'] = ref['links']
		
        info = {
          "filters"   => [Jekyll::Filters],
          "registers" => { :site => site, :entry => ref }
        }
        liquid_template.render!(payload, info)
        
      end
```

**Comment by inukshuk** [comment]
Can you try if the commit above works for you?

**Comment by JoostvanPinxten** [comment]
Yep, that works too :-) Thanks!
