### ISSUE TITLE
Title of detail pages

### ISSUE THREAD

**Issue by reitzig** [inukshuk/jekyll-scholar#120]
Currently, `page.title` of the detail pages seems to be empty. That's no good!

Using the `title` entry of the publication may be a reasonable default, or `author: title` (which would make more sense for references, less sense for publication lists). Either way, there should probably a method to override.

**Comment by inukshuk** [comment]
Could you add a failing test case for this?

(This maybe somewhat related to #118)

**Comment by reitzig** [comment]
I'm not sure what you need to see. If I use `{{ page.title }}` in the template I use for detail pages, I get nothing. See e.g. [here](http://reitzig.github.io/publications/RW2015b); note the absence of `page.title` in the `<title>` element (what you see is `site.title`, compare e.g. with [this](http://reitzig.github.io/ramblings/); both use the same basic HTML template).

**Comment by inukshuk** [comment]
What would you expect the page title to be though? The title of the BibTeX entry? (What if there's no title?)

**Comment by reitzig** [comment]
As I wrote in my original post, I think title or a combination of author and title would be a reasonable default.

Afaik, there is no BibTeX entry type for which title was *not* mandatory. So if you assume valid BibTeX as input (do you check for that?), that should not be a problem. Otherwise, using the empty string is not worse than what we have now.  
(At least I don't see a way to set/force some title, at all.)

**Comment by inukshuk** [comment]
We can add this if you think it is necessary; I don't quite see why it is though. On a regular page the title would be set in the front matter, right? So if you want to share templates/layouts couldn't you write something like ``{{ page.title || page.entry.title }}`? What we would do, effectively, to implement this feature request is to expose the title to the template twice using different variable names. It is not a big deal, but do you think it's worth it?

**Comment by reitzig** [comment]
I can only speak for myself. For me, the experience breaks if I have to update my template because a generated page is not assigned a useful title. What you propose feels wrong, too, because a) the second part makes no sense for most pages or, worse, b) it might do wrong things for pages generated by other plugins that *also* happen to define `page.entry.title` (but not `page.title`).

So yes, I think Jekyll-Scholar should provide a page title. If you don't think it's worth the effort (especially if there is to be any amount of customization options), I doubt I can change your mind. :) 

Sadly, I don't see a way to work around this (without changing the installed plugins). Maybe a Jekyll hook would work: if `page.title` is not there but `page.entry` looks like it comes from Scholar, then set `page.title`. (Can hooks change page information? Worth a try, maybe.)

**Comment by inukshuk** [comment]
The details page layout is supposed to be a layout file; you have used this feature in an interesting way, by referring to your regular layout in the layout's front-matter. This is a really cool idea, but by doing this, I think it is reasonable to expect that your layout be able to handle both regular pages and generated detail pages.

Look, it's easy to add 'page.title' but then, what about other front-matter variables like date, published, category, etc. -- should we set those too? Detail pages were always intended to be rendered with their own layout. You want to render them with the same layout you are using for other pages, which, again, I think is a really cool idea, but since you're doing this by choice I don't see why you can't make your layout aware of the fact that the current page might be a detail page. This way, you can make all the customizations that are necessary, can't you? Maybe I'm missing something, but why is it so hard to work around this?

**Comment by inukshuk** [comment]
OK I figured it does not hurt, so we are also exposing the entry's title as the page title. If you need customization you can do it in the template or a patch (either way should be trivial).

Landed in 5.4.1

**Comment by reitzig** [comment]
> Detail pages were always intended to be rendered with their own layout.

Ah, I see. I figured since detail pages share most elements with every other page -- header, navigation, footer, ... -- there was little use in effectively duplicating the layout, causing redundancy and the need to keep both in sync.  
(Thanks for checking my sources, I'd never have thought to mention that!)

> OK I figured it does not hurt, so we are also exposing the entry's title as the page title.

Cool, thanks! Should I feel I need more, I'd probably go ahead, implement a `details_title` option (which could be set to `entry.title` or `"{{ entry.author }}: {{ entry.title }}"` or even `entry.pagetitle`, using a non-standard BibTeX value) for Jekyll-Scholar and PR you. :) Till then!
