### ISSUE TITLE
How do I query entries WITHOUT certain fields?

### ISSUE THREAD

**Issue by kristiannordestgaard** [inukshuk/jekyll-scholar#126]
I have created two fields, `seneste` and `oevrige`. Then I do: 

`{% bibliography --query @*[seneste] %}`

and

`{% bibliography --query @*[oevrige] %}` 

... to get the entries with the two fields, respectively. Now I want a list of the remaining entries. I tried playing around with `!`, but no luck so far. What should I do?

**Comment by inukshuk** [comment]
You can probably use a wildcard match: `@*[seneste !~ . && oevrige !~ .]`

**Comment by kristiannordestgaard** [comment]
Thanks, works like a charm!
