### ISSUE TITLE
commit ：github build failed 

### ISSUE THREAD

**Issue by symphonyh** [inukshuk/jekyll-scholar#135]
gem 'jekyll-scholar', '~>5.5.1' localhost run is very good ,But commit github page build failed

github: page build failed "recognized Liquid tag "
The problem lies in :

{% bibliography %}

and {% cite cesaire_discourse_2001 -r /bibliography.html %}
Where is the consultation problem? thank you!

my project：https://github.com/symphonyh/symphonyh.github.com

**Comment by edgemaster** [comment]
jekyll-scholar cannot be deployed directly to GitHub Pages, please read the documentation for the jekyll bundle you are using: https://elotroalex.github.io/ed/documentation.html#publishing-github-pages, in which it notes to use the `rake blog:publish` command.
