### ISSUE TITLE
baseurl breaks citation links

### ISSUE THREAD

**Issue by timetravellers** [inukshuk/jekyll-scholar#136]
If you have baseurl defined in the jekyll config file this breaks the in page links:

e.g. 
If `baseurl: /research` is defined in the Jekyll `_config` file:
If I am on a page called `projects.html` the link for `{% cite au %} ` should be `jm.com/research/projects.html#au`
The resulting link is `jm.com/research#au` and is missing the page

**Comment by inukshuk** [comment]
Ah, yes, I was worried this might happen because of #124 -- @elotroalex can you take a look? It's probably a good idea to take a look at what Jekyll does internally when creating links.

**Comment by elotroalex** [comment]
Can you assign this issue to me @inukshuk? I'll take a look at it. I've been thinking about this, and I have a few ideas I want to test that might solve this issue.

**Comment by elotroalex** [comment]
And I meant the problem in #136

**Comment by elotroalex** [comment]
I just put in a pull request. Hopefully this solves it, and improves it even.

**Comment by elotroalex** [comment]
see: elotroalex#137

**Comment by inukshuk** [comment]
I think so. Thanks!

**Comment by timetravellers** [comment]
This works great thanks!
