### ISSUE TITLE
cite from more than one bib file

### ISSUE THREAD

**Issue by espinielli** [inukshuk/jekyll-scholar#138]
I failed to find in the tests or issues whether this is possible:

* I have 3 `.bib` files for better management of many bibliographic entries (there are no duplicates in the set of all entries from the files combined)
* In my markdown pages I would like to `cite` an entry in one of those `.bib` files.
  I used something like `{% cite abc %}` and at the end of the page I did put `{% bibliography --cited_in_order %}`
* In my configuration I only specify the `source` directory where the `.bib` files are stored. I do not specify the `bibliography` (I tried to put a list of `.bib` files but got compilation errors...)

The rendered doc shows `missing reference`

What am I doing wrong?

I see that there is the `--file` option for `bibliography` but I haven't managed to make it work for citations...i.e. `{% cite --file myfile1 abc %}`

**Comment by inukshuk** [comment]
You just need to specify the key as the first argument to `cite` -- i.e., `cite abc --file myfile` works.

**Comment by espinielli** [comment]
Thanks! this worked great:

> text, text, text, {% cite eu:691/2010 --file legislation %}
> other text, other text {% cite hfe:pru --file aviation %}
> ...
> # References
> {% bibliography --cited_in_order --file aviation --file legislation %}

Maybe worth for the doc/README...(or the tests :-)

Again thanks
