### ISSUE TITLE
Crossref

### ISSUE THREAD

**Issue by kristiannordestgaard** [inukshuk/jekyll-scholar#141]
Hi,

I have tried every variation of `crossref` I could think of, and it still won't work. What I'm trying to add is a list of poems that are in the same book. 

The simplest form I can think of: 

```
@inbook{poem1,
title = {A poem},
author = {Some person},
crossref = {collection1}
}

@book{collection1,
title = {Collection of poems},
editor = {Another person},
year = {2016},
publisher {A company}
}
```

I tried with `chapter` and `incollection` and so on, but still no luck. I hope you can provide an MWE.

**Comment by inukshuk** [comment]
What is the problem exactly?

**Comment by kristiannordestgaard** [comment]
When I do `{% bibliography --query @*[author ^=  some person] %}`

For the entry `poem1`, I get what's in `poem1` but nothing from `collection1` in the output. I tried several styles but no luck so far.

**Comment by inukshuk** [comment]
Ah, OK, cross references are not resolved for queries... We could discuss adding support for this to bibtex-ruby but it would have to be explicitly enabled I think.

Furthermore, it seems that we don't inherit all values when exporting the item data to the cite processor... that is something we should definitely do, I'll take a look!

**Comment by kristiannordestgaard** [comment]
Thanks, I thought it was me doing something wrong! I'll just keep it in a single `inbook` entry for now, then!

**Comment by inukshuk** [comment]
OK I pushed an update to bibtex-ruby... if you make sure to use version 4.3.0 then inherited fields should show up when citing references (queries on inherited fields don't work, though, like I mentioned before).
