### ISSUE TITLE
Jekyll Scholar breaks with Jekyll v3

### ISSUE THREAD

**Issue by se4u** [inukshuk/jekyll-scholar#145]
the following fix on line 70 of `footnotes.rb` fixes it.

    - converter = site.getConverterImpl(::Jekyll::Converters::Markdown)
    + converter = if site.respond_to?(:find_converter_instance)
                      site.find_converter_instance(::Jekyll::Converters::Markdown)
                    else
                      site.getConverterImpl(::Jekyll::Converters::Markdown)
                    end
        
See https://github.com/jekyll/jekyll/issues/3662 for details about the fix.

**Comment by inukshuk** [comment]
Uh, that's cool, but I don't think we have a `footnotes.rb`...?

**Comment by edgemaster** [comment]
Jekyll Scholar works for me with Jekyll v3.1.2 (latest release).

**Comment by se4u** [comment]
Sorry about this false alarm.  The problem was in a different plugin `jekyll-scholar` and I mistakenly opened this issue here.
