### ISSUE TITLE
Can not load local jekyll scholar

### ISSUE THREAD

**Issue by tmensink** [inukshuk/jekyll-scholar#146]
I would like to use a local copy of jekyll-scholar.

Therefore, in `_plungins/scholar.rb` I have the following:

`$:.unshift '/home/my/path/jekyll-scholar/lib'`
`require 'jekyll/scholar'`

The error message is:
`Dependency Error: Yikes! It looks like you don't have /home/tmensink/documents/research/website/uva20/_plugins/scholar.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- bibtex' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! `

I have tried to install a `bibtex` gem, but that yields the following error `Could not find a valid gem 'bibtex' (>= 0) in any repository'

There are a few related gems, which I have installed using:
`gem install bibtex-ruby csl-styles citeproc-ruby`
But that does not solve the problem.

**Comment by inukshuk** [comment]
Is your local copy really at `/home/my/path/jekyll-scholar/lib`?

The gem `bibtex-ruby` should provide 'bibtex' so that's alright.

What happens if you run just `ruby -r_plugins/scholar.rb -e "puts BibTeX::Version::STRING"`? Or if you run `ruby -rbibtex -e "puts BibTeX::Version::STRING"`

**Comment by tmensink** [comment]
Thanks for your swift response.

1. Yes, pretty sure that is correct
2. `$ ruby -r_plugins/scholar.rb -e "puts BibTeX::Version::STRING"`, results in an error:
`/home/user/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file -- _plugins/scholar.rb (LoadError) from /home/user/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in 'require'`
3. `$ ruby -rbibtex -e "puts BibTeX::Version::STRING"`, returns:
`4.3.0`

**Comment by inukshuk** [comment]
You need to run the second one in your project folder (or provide the full path to `_plugins/scholar`) otherwise it won't find the file.

**Comment by tmensink** [comment]
For sure. I did that.

```
~/Downloads/jekyll-scholar/lib $ pwd
/home/me/Downloads/jekyll-scholar/lib

~/Downloads/jekyll-scholar/lib $ cd ~/Downloads/web

~/Downloads/web $ ruby -rbibtex -e "puts BibTeX::Version::STRING"
4.3.0

~/Downloads/web $ cat _plugins/scholar.rb 
$:.unshift '/home/me/Downloads/jekyll-scholar/lib'
require 'jekyll/scholar'

~/Downloads/web $ ruby -r_plugins/scholar.rb -e "puts BibTeX::Version::STRING"
/home/me/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- _plugins/scholar.rb (LoadError)
	from /home/me/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

What does work is the following (adding ./ to the path):
```
~/Downloads/web $ ruby -r./_plugins/scholar.rb -e "puts BibTeX::Version::STRING"
4.3.0
```

But I still get the error:
```
~/Downloads/web $ bundle exec jekyll build
Configuration file: /home/me/Downloads/web/_config.yml
  Dependency Error: Yikes! It looks like you don't have /home/me/Downloads/web/_plugins/scholar.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- bibtex' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
jekyll 3.1.1 | Error:  /home/me/Downloads/web/_plugins/scholar.rb
```

**Comment by inukshuk** [comment]
Ah, yes, that's right. you need to add the './' there. So the result of this shows that you can load jekyll-scholar just fine when you call it directly. Might be related to the way you use bundler. Instead of modifying the path in scholar.rb you could try to set the local path to jekyll scholar in your Gemfile.

**Comment by edgemaster** [comment]
The bundler documentation gives a bit more information about how to configure it to get a gem from a particular git repository, or local source: http://bundler.io/git.html#local

**Comment by tmensink** [comment]
Indeed, this worked. I've used:
`gem "jekyll-scholar", :path => "/home/path/to/my/jekyll-scholar/"`

Thanks!
