### ISSUE TITLE
Citation for bible-style locators

### ISSUE THREAD

**Issue by jamestomasino** [inukshuk/jekyll-scholar#147]
I have several older works I'm citing that use a chapter/verse notation rather than page number, similar to citing the bible. It looks like you have locator support for pages, but not for chapter/verse. I also don't see a way to override the citation text in the `cite` command like you have with `cite_details` where I could manually enter the formatting. I tried using the later command, but it doesn't trigger the bibliography to show at the bottom and links to a bib details page rather than the footnotes.

Is it possible to allow for a text-override to the `cite` command output? For instance:

`{% cite key -t (Some custom string) %}`

**Comment by inukshuk** [comment]
Citations are rendered using citeproc-ruby based on the given CSL style. See [labels](http://docs.citationstyles.org/en/stable/specification.html#label) and [locators](http://docs.citationstyles.org/en/stable/specification.html#locators) for more details on which variables you can use -- these include both chapter and verse (although citeproc-ruby should let you pick any available term anyway).

Having said that, we did not expose the option to override the locator label to jekyll-scholar so you need to update to 5.8.0 to make this work (thanks for spotting this!): basically, you can pass a the `-L` or `--label` option to specify the locator label (which defaults to 'page') for each locator. The way this works is that citeproc-ruby will look at the `locator` option to determine the singular or plural form of the term and at the given CSL style for long, short, form etc. So `{% cite key -L chapter -l 4-5 %}` would render something like `chapters 4-5` or `chaps. 4-5` depending on your CSL style.

To adjust the format of the citation you would normally adjust the CSL style.
