### ISSUE TITLE
ol reversed

### ISSUE THREAD

**Issue by andrewning** [inukshuk/jekyll-scholar#148]
I have been using the option:
bibliography_list_tag: ol reversed
which has been great.  It renders the numbering in my bibliography in reverse order.

However, since updating to jekyll 3.x this no longer works.  The opening tag is created correctly, but the closing tag is created as:
`"&lt;/ol reversed&gt;"`
which messes up the rendering.

Any ideas?

**Comment by edgemaster** [comment]
As far as I can tell, there has never been explicit support for attributes for this configuration option. I suspect that Jekyll may have changed its HTML transformer in the meantime to make it more permissive.

I assume that if using numbered citations inline then the numbering will be out of sync with the content body.

One approach to fixing this could be to add a config parameter like "bibliography_list_attributes", accepting a hash of attributes to set. I've linked a code commit to this issue, does this look like it would meet your needs?

**Comment by andrewning** [comment]
Thanks for the help.  I tried it but I get the error: "Liquid Exception: no implicit conversion of String into Hash".  I'm not familiar with Liquid.

**Comment by andrewning** [comment]
So I tried passing in a hash, and then the two entries will merge properly but the output isn't what I was looking for.  It will be something like

`<ol ol="reversed" class="bibliography">`
when I need:
`<ol reversed class="bibliography">`

**Comment by andrewning** [comment]
Nevermind.  I realized just need to pass a hash with an empty value.  I'm not familiar with ruby so I didn't catch on to this earlier.

**Comment by edgemaster** [comment]
Sorry, I should have given a usage example. If this is good for you, I'll
push it into the main repository with a couple of tests.

**Comment by inukshuk** [comment]
@edgemaster by the way thanks a lot for helping out! Just wanted to say your more than welcome to add yourself to the Gemspec if you have a Rubygems account -- we try to follow semver, though like everything else around here not religiously -- and/or to the Readme/License.

**Comment by andrewning** [comment]
Yes, it works well for me. Thanks!

- Andrew




On Wed, May 11, 2016 at 6:26 AM -0700, "Thomas Wood" <notifications@github.com> wrote:










Sorry, I should have given a usage example. If this is good for you, I'll

push it into the main repository with a couple of tests.

**Comment by edgemaster** [comment]
I've now merged this into master. There were no tests for the existing configuration options. I've opened a [TODO ticket](edgemaster#2) for me to add some in the future.
