### ISSUE TITLE
Add global option to add citation style as class to bibliography <ol>

### ISSUE THREAD

**Issue by JoostvanPinxten** [inukshuk/jekyll-scholar#154]
In my template I am hacking around some rendering issues for the IEEE csl, and I find that it can be useful for my template if I could detect in CSS what style is being used.

I.e. a way to determine whether or not the hack should be applied. Of course in liquid I can do this with `{% if site.scholar.style == "ieee" %}`. I thought that I saw somewhere that I can also manually append a class to each generated bibliography in Liquid (but I cannot find the filter anymore).

Would this be acceptable? If so, I'll provide a merge request sometime soon.

**Comment by inukshuk** [comment]
You mean you would like to add a class indicating the current style to the bibliography tag by default? I think that's fine, however, users defining their own template would have to add the class manually (like you describe above). So, just to understand this correctly: you want to add it to the default output, because it's overkill to add your own liquid template just to add the class, is that right?

**Comment by JoostvanPinxten** [comment]
Yes, that's exactly what I'd need to have. It think it's not too polluting either, as it can be default-off, and it's not in the way for other things. 

I was thinking of putting this extra class on the `<ol class="bibliography">` tag. Is it possible to overrule that somewhere? Because then it will be somewhat conflicting.

**Comment by inukshuk** [comment]
You would add the extra class [here](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/tags/bibliography.rb#L96). I would suggest to add an extra helper to the utilities file to compose the class names if it gets too complicated.

**Comment by JoostvanPinxten** [comment]
I'm still getting used to thinking with Jekyll. I now generate the .css file, and check the same tag as I check in the templates. This currently solves my issue.

I'm not sure what other use case would warrant this change now...
