### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by rabernat** [inukshuk/jekyll-scholar#156]
I love jeykll-scholar and have been using it for over a year in my [site](http://rabernat.github.io).

Recently, something changed in my system configuration (probably updating to El Capitan), and it broke my jekyll / jekyll-scholar setup. `jekyll` itself had disappeared, so I reinstalled it by calling
```bash
sudo gem install jekyll
sudo gem install jekyll-scholar
```

I can confirm that jekyll-scholar is installed and can be required
```bash
$ irb
irb(main):001:0> require 'jekyll/scholar'
=> true
```

However, when I try to build my site, I get the following
```bash
$ jekyll build 
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/rpa/Sites/jekyll/rabernat.github.io/_config.yml
  Dependency Error: Yikes! It looks like you don't have /Users/rpa/Sites/jekyll/rabernat.github.io/_plugins/ext.rb or one of its dependencies installed.
In order to use Jekyll as currently configured, you'll need to install this gem.
The full error message from Ruby is: 'cannot load such file -- jekyll/scholar'
If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
jekyll 3.1.6 | Error:  /Users/rpa/Sites/jekyll/rabernat.github.io/_plugins/ext.rb
```

The contents of `_plugints/ext.rb` are
```ruby
require 'jekyll/scholar'
```

This is very frustrating--all evidence suggests that the jekyll-scholar gem is installed, yet it can't be required by jekyll. I am totally stuck.

Additional system info
```bash
$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
$ jekyll --version
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
jekyll 3.1.6
```

**Comment by rabernat** [comment]
I realized I just had to delete the `Gemfile.lock` file, then everything worked fine.

**Comment by inukshuk** [comment]
Glad you figured it out. Cool site (and research)!

**Comment by jacobnzw** [comment]
Seems like my problem was solved by using `gem: ['jekyll/scholar']` instead of `gem: [jekyll-scholar]` in the `_config.yml`. 

I suppose that's because `require 'jekyll/scholar'` and not `require jekyll-scholar` is in `_plugins/ext.rb`.

**Comment by DateBro** [comment]
@rabernat Thanks for your issue and solution, I solved my same problem with your solution of deleting the file. 🎉
