### ISSUE TITLE
Error message on El Capitan when I try to serve jekyll

### ISSUE THREAD

**Issue by Andrewepstein** [inukshuk/jekyll-scholar#159]
Hello there,

I am new to all this so please excuse my ignorance.  Anyhow, I am trying to build a website using Jekyll.  After entering "sudo gem install jekyll" (not including the quotes), I received a long stream of code indicating that the documentation was being successfully installed.  However, when I then went to serve the files, I received this message: 

ANDREWs-iMac:blog andrewepstein$ jekyll serve
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.2.1/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
ANDREWs-iMac:blog andrewepstein$ ls
Gemfile		_posts		css		index.html
_config.yml	about.md	feed.xml

Not sure what this all means and any help would be greatly appreciated.  Thanks

**Comment by inukshuk** [comment]
Hope you've figured this out in the meantime, but it looks like you have not installed bundler yet (e.g., `sudo gem install bundler`). I would suggest to look for tutorials on setting up jekyll in general.
