### ISSUE TITLE
Generate a PDF file from the markdown page using jekyll-scholar

### ISSUE THREAD

**Issue by i2000s** [inukshuk/jekyll-scholar#164]
I wonder if there is a way to export a markdown page to a nice PDF file where jekyll-scholar is used? To be specific, I have defined some customized field style for `abstract`, `bibtex`, `links` and so on for the publications appearing nicely on a Jekyll webpage; but when I want to export the publication page to a pdf file as my CV, I don't want to show the self-defined `abstract`, `bibtex`, `links` and other fields of each publication entry. I have tried Printing from a browser to pdf, but it doesn't work. Pandoc might be a good tool to implement this function, but it seems I have to write some script to filter out those unwanted bibtex fields. Even without filtering out those fields, I cannot use Pandoc to convert the markdown file to pdf directly because Pandoc cannot recognize the jekyll-scholar codes as I have tried. Any idea on how to generate the PDF file, or should jekyll-scholar provide some functionality to make it possible/easy to generate a nice PDF file from a markdown jekyll file where jekyll-scholar is used? 

A jekyll page using the customized style page can be found [here](http://i2000s.github.io/pubs/). Thank you!

**Comment by inukshuk** [comment]
The easiest solution for you is probably to create a second page which contains only those elements which you want to include in the PDF. Then you can create a PDF from that page using a html-to-pdf library or your browser's print page function.

Alternatively, you can generate PDFs from Ruby, but I think you will get quicker results by creating HTML and using CSS for styling.

I can imagine that there would be interest in such a feature, but it would probably have to be highly configurable and therefore not an easy task.

**Comment by i2000s** [comment]
As a matter of fact, I am using the HTML-to-PDF method via Pandoc. I have to manually exclude unwanted fields to make the pdf converter work nicely enough. I plan to make some code to automate the process by pushing changes of the CV page to a dedicated branch and then I can focus on only trimming down the updated information in that branch and do the convert. 

Anyway, I am not an expert in Ruby and Haskell, but I appreciate if anyone can help integrate this nice Jekyll-Scholar tool with the Pandoc-ruby or other tools to avoid this hassle of trimming up extra HTML files, that would be nice. Then all these process could be handled easily by Travis-CI and similar automation tools. Thanks.

**Comment by i2000s** [comment]
I think the easiest way to implement this feature is to provide an option in the `{% bibliography %}` code that a second bibtex template file can be used... Is this easy enough to do in jekyll-scholar? This might be useful for customizing bibliography styles on different pages.

**Comment by i2000s** [comment]
Just another thought: is that possible for jekyll-scholar to generate a markdown file with all those bibtex entries formatted before converting the page into html? In that way, I might be able to filter out useless information in the markdown file using pandoc and then convert it to pdf.

**Comment by inukshuk** [comment]
Why don't you give the things you want to hide a certain class name (in your template) and add a print-only css which simply hides those fields?
