### ISSUE TITLE
Descending the numbering

### ISSUE THREAD

**Issue by i2000s** [inukshuk/jekyll-scholar#165]
Hey,

I am pretty exhausted with numbering a list of publications in bibliography. I want to have the latest publication listed as the first one but with the largest index number. That is to say, I would like to have a list of my publications like

```
3. paper 1 (2016).
2. paper 2 (2015).
1. paper 3 (2014).
```
I think the problem is very very easy to solve if I can modify the html code directly. I only need to add ` reversed="reversed"` as a property of `ol` lists of the class "bibliography". I have no clue how to do this in jekyll-scholar code. I have tried javascripts as well as changing ordering parameters of jekyll-scholar for the whole day. No luck so far.

The page I am working on is [here](http://i2000s.github.io/pubs/) with source code at [this repo](http://github.com/i2000s/i2000s.github.io). 

Can you shadow a light on this? Or Jekyll-Scholar doesn't have this functionality? I have seen [this issue](https://github.com/inukshuk/jekyll-scholar/issues/148), but still not sure how to use it. Thanks.

**Comment by inukshuk** [comment]
You can add this to your config:

    bibliography_list_attributes:
      reversed: "reversed"

This should add the reversed attribute to the `<ol>`.

**Comment by i2000s** [comment]
@inukshuk Thank you, that works! 

Along the line, is there any way to add the entry.url hyperlink to the title of an entry? I didn't make it work in making a bibtex template so far. Sorry for branching out.

**Comment by inukshuk** [comment]
You mean the title inside the formatted reference? We'll have to implement hooks in citeproc-ruby to make something like that easily possible (right now you'd have to write hacks to achieve these sort of things). So, no, there is no easy way to do that.

**Comment by i2000s** [comment]
Thank you! I will close this issue now.
