### ISSUE TITLE
Getting a formatted entry.author

### ISSUE THREAD

**Issue by basnijholt** [inukshuk/jekyll-scholar#166]
I would like to get `entry.author`, but in a formatted way, because right now it's literally the entry from the bib file, which also makes sense.

Is it possible to get just the author list from a particular style, (for example from `apa.csl`)?

Background:
I don't want to adhere to a particular csl style, because I have my own (`bib.html`)[https://github.com/basnijholt/nijholt.org/blob/f961aabbe1b87da95aa3a69418832683fdb9f40b/_layouts/bib.html] where I link the journal to the website and have a pdf from `arXiv`.

It looks something like this:
<img width="777" alt="screen shot 2016-09-20 at 15 06 14" src="https://cloud.githubusercontent.com/assets/6897215/18671303/ef5f696a-7f43-11e6-8223-6674a7ae750d.png">

As you can see, it's not really what one would want, due to all the redundancies.

**Comment by inukshuk** [comment]
I would suggest to adjust the CSL style: this is really what CSL styles are meant for -- you can adjust the format to your requirements and it's probably easier to format names in CSL than in Ruby.
