### ISSUE TITLE
Missing references for bib from file

### ISSUE THREAD

**Issue by heathermiller** [inukshuk/jekyll-scholar#173]
Hi, first off, thanks for the great plugin :)

I'm having an issue with citations of a bibliography read from file. 

Here's the bibliography I'm trying to cite, `_bibliography/example.bib`:
https://github.com/heathermiller/dist-prog-book/blob/master/_bibliography/example.bib

I have the following two citations in my markdown file: `{% cite Uniqueness %}` and `{% cite Elsman2005 Kennedy2004 %}`

Here's the markdown file where I cite these three entries:
https://github.com/heathermiller/dist-prog-book/blob/master/example.md

Here's the generated page:
http://dist-prog-book.com/example.html

Notice the "(missing reference)"s everywhere. E.g., 

<img width="718" alt="screen shot 2016-10-17 at 9 28 43 am" src="https://cloud.githubusercontent.com/assets/687163/19439616/b8945e5e-944c-11e6-9d22-f9063eb17fb5.png">

I'm at a bit of a loss. The bibliography is found and rendered. So it's there. Citations just don't seem to work.

What am I doing wrong?

**Comment by inukshuk** [comment]
Is `example.bib` your main bibliography (set in the jekyll scholar settings)? Otherwise you have to add `--file example` to each `cite` tag.

It would be great to parse the front-matter options on each page to make it easier to override the defaults, but unfortunately that has not been implemented yet.

**Comment by heathermiller** [comment]
Thanks for the clarifications. I hadn't realized this was required simply because it wasn't mentioned in the README. 

So, I just updated the README to reflect this info. Thanks for your help!

**Comment by heathermiller** [comment]
Clarified in #174

**Comment by edgemaster** [comment]
(See also #95 for the feature request for frontmatter options)
