### ISSUE TITLE
Single file for references?

### ISSUE THREAD

**Issue by lorentrogers** [inukshuk/jekyll-scholar#177]
Hi all, I'm not sure if this is missing from the documentation, or if things don't work this way: is it possible to have a single `references.bib` file with all my citations in it? I have many pages that cite from a shared collection of sources, but each page only cites a few at a time. Do I need to make separate duplicate reference files with all the variations I need? Is there a way to make jekyll-scholar only render the references that are cited on that page? (At the moment, `{% bibliography %}` is rendering all sources on every page.)

**Comment by JoostvanPinxten** [comment]
{% bibliography --cited %} see readme.md

**Comment by lorentrogers** [comment]
Ha! Thanks - apparently my brain was total mush yesterday. I completely missed that paragraph!

**Comment by JoostvanPinxten** [comment]
No problem :-) happy to help!
