### ISSUE TITLE
cannot load such file -- jekyll/scholar

### ISSUE THREAD

**Issue by dlindo** [inukshuk/jekyll-scholar#182]
Hello - Could you please help with this issue? Pls find below what I did:
1) 
dyn-160-39-16-227:dlindo.github.io davidlindo-atichati$ rake publish
rake aborted!
cannot load such file -- jekyll/scholar
/Users/davidlindo-atichati/Desktop/dlindo.github.io/Rakefile:6:in `require'
/Users/davidlindo-atichati/Desktop/dlindo.github.io/Rakefile:6:in `<top (required)>'
(See full trace by running task with --trace)

2)
dyn-160-39-16-227:dlindo.github.io davidlindo-atichati$ rake publish --trace
rake aborted!
cannot load such file -- jekyll/scholar
/Users/davidlindo-atichati/Desktop/dlindo.github.io/Rakefile:6:in `require'
/Users/davidlindo-atichati/Desktop/dlindo.github.io/Rakefile:6:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/rake_module.rb:25:in `load'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/rake_module.rb:25:in `load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:604:in `raw_load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:89:in `block in load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:88:in `load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:72:in `block in run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:70:in `run'
/usr/bin/rake:37:in `<main>'

3)
dyn-160-39-16-227:dlindo.github.io davidlindo-atichati$ irb
irb(main):001:0> require 'jekyll/scholar'
=> true

Here are the first 6 lines of my Rakefile:
require "rubygems"
require "tmpdir"

require "bundler/setup"
require "jekyll"
require "jekyll/scholar"

I tried to debug following this related thread (https://github.com/inukshuk/jekyll-scholar/issues/61) but did not work. Many thanks!

**Comment by inukshuk** [comment]
Have you added the gem `jekyll-scholar` to your Gemfile?

**Comment by dlindo** [comment]
I am not sure if I did, but it looks like it is there. Correct?

dyn-160-39-16-227:gems davidlindo-atichati$ pwd
/Library/Ruby/Gems/2.0.0/gems

dyn-160-39-16-227:gems davidlindo-atichati$ ls
addressable-2.5.0           liquid-3.0.6
bibtex-ruby-4.4.3           listen-3.0.8
bundler-1.14.3              mercenary-0.3.6
citeproc-1.0.5              minima-2.1.0
citeproc-ruby-1.1.6         namae-0.11.3
colorator-1.1.0             pathutil-0.14.0
csl-1.4.5                   public_suffix-2.0.5
csl-styles-1.0.1.7          rake-0.9.6
ffi-1.9.17                  rb-fsevent-0.9.8
forwardable-extended-2.6.0  rb-inotify-0.9.8
jekyll-3.4.0                rdoc-4.0.0
jekyll-feed-0.8.0           rouge-1.11.1
jekyll-paginate-1.1.0       rubygems-update-2.6.10
jekyll-sass-converter-1.5.0 safe_yaml-1.0.4
jekyll-scholar-5.9.1        sass-3.4.23
jekyll-watch-1.5.0          test-unit-2.0.0.0
kramdown-1.13.2             unicode-0.4.4.2
latex-decode-0.2.2

**Comment by inukshuk** [comment]
Yes, you installed the gem (that's why, when you require it in IRB it loads fine), but you may not have added it to your bundle, hence you're problems after you require `bundler/setup`. You need to add `jekyll-scholar` to your Gemfile and run `bundle install` -- you can check if bundler knows about it by running `bundle show jekyll-scholar`.

**Comment by dlindo** [comment]
Wonderful, it worked! Thanks very much!
