### ISSUE TITLE
Add mechanism to iterate in liquid over bibliography entries

### ISSUE THREAD

**Issue by mamoll** [inukshuk/jekyll-scholar#185]
I'd like to make my publications searchable based on words in the title, abstract and keywords fields. It seems like lunr.js might be useful for that (see http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/). If there's an easy way to just generate a JSON file as part of the build process and have lunr.js just read that, that'd also be good.

**Comment by inukshuk** [comment]
It should be fairly easy to generate a JSON file. In fact, converting BibTeX to CSL/JSON is already supported by bibtex-ruby.

**Comment by mamoll** [comment]
Thanks. It's not immediately obvious to me, though, how I can turn my `bibliography.bib` into `bibliography.json` or something else I can use to connect things to lunr.js.

**Comment by mamoll** [comment]
Perhaps this will work as preprocessing step, before running Jekyll:
```
require 'bibtex'
File.open('_data/publications.json', 'w') { |file| file.write(BibTeX.open('publications.bib').to_json) }
```
The ticket can be closed, I think.
