### ISSUE TITLE
Feature Request: Formatting/replacing specific string name in references list

### ISSUE THREAD

**Issue by ptsgmartins** [inukshuk/jekyll-scholar#187]
It would be nice to be able to format all occurrences of a specific string in the references list (namely, an author's name, e.g. making one's own name bold).

1. **Smith, J.** (2016). Paper. *Journal, 5*(6), 4–11.  
1. Doe, J. & **Smith, J.** (2015). Another paper. *Another Journal, 2*(3), 9–23.

Perhaps there's already a way of doing this?

**Comment by ptsgmartins** [comment]
I went ahead and used this script, which works fine if placed after the content (and could of course be tweaked to be more precise in scope):
```
$("body").html($("body").html().replace(/string/g,'<b>new string</b>'));
```
So while it would be nice to have the option in jekyll scholar, something like:
```
scholar:
  replace_string: [string, new string]
```
It's probably too generic to be worth it.

**Comment by inukshuk** [comment]
Yes, to do this 'the right way' we'll need to add hook-support to citeproc-ruby (i.e., callbacks that can be triggered at specific nodes of the CSL style) -- this way you could add special formatting to any part of the reference.

Barring that, if you know/control your bibliography, it's easy to add a more specific solution -- like yours, I think that's perfectly fine.

You can see a similar version here too: http://stackoverflow.com/questions/28020553/highlight-a-certain-author-in-references/28069465#28069465

**Comment by ptsgmartins** [comment]
Good to know I am not the first to wonder about this.

Actually I like that other solution must better. Thanks for sharing! It's closer to what I had in mind in terms of usability. I didn't know you could do that with Liquid! (now I went ahead and actually looked at the Liquid documentation, and see that a lot more than I thought can be done)
