### ISSUE TITLE
Citation insertion style

### ISSUE THREAD

**Issue by theo-m** [inukshuk/jekyll-scholar#195]
I am playing with the citation styles, linking directly to csl files like so:

```yaml
scholar:
  style: https://raw.githubusercontent.com/citation-style-language/styles/master/chicago-author-date.csl
```

Which works fine, but I can't figure out how to remove the parentheses. They are on whatever the csl file. I can't find documentation on this.

Thanks for your work

EDIT:
I'm adding an example:

```
.. computationally expensive idea up until (Mikolov, Chen, Corrado, & Dean, 2013) ...
```

**Comment by inukshuk** [comment]
The parentheses are part of your chosen style. If you want to omit them, you will have to pick an appropriate style, or adjust the style to your needs. In this case, you'd [just remove the prefix and suffix](https://github.com/citation-style-language/styles/blob/master/chicago-author-date.csl#L603) and use this version of the style.

There is also a special variant of citing which [suppresses author names](https://github.com/inukshuk/jekyll-scholar#suppressing-author-names); you'd usually do this if you already mentioned the author names in the text — given Chicago style this would result in `(2013)` (with parentheses, just without the authors, which, presumably you already mentioned).

**Comment by theo-m** [comment]
Ok thank you very much ! Just what I expected :+1:
