### ISSUE TITLE
Extract formatted author names

### ISSUE THREAD

**Issue by rohitdureja** [inukshuk/jekyll-scholar#197]
I was wondering if there is a way to extract the author in a formatted citation entry. For example, if the citation is (in ACM style) "John Doe, Alice Y. Doe, and Bob J. Summer. 2017. Our first paper together. Proceedings of International Springfield Conference (SC).", I want to be able to extract "John Doe, Alice Y. Doe, and Bob J. Summer".

Using entry.author returns the authors as they appear in the bibtex entry, i.e., lastname, firstname

Thanks for the help!

**Comment by inukshuk** [comment]
I'm afraid that's currently not possible, no. You would have to format the names again, according to your style's rules (you could even add a custom CSL file which uses only the `names` nodes from the CSL style you're using) or parse them out of the whole reference string.
