### ISSUE TITLE
Items tag with custom class

### ISSUE THREAD

**Issue by emir-munoz** [inukshuk/jekyll-scholar#199]
I'm trying to assign a custom class to the item `<li>` tags which depends on an entry field. For example, I have a BibTeX entry with a custom field `type = {conference}`, and I would like to generate the following HTML entry:
```html
<li class="conference">
    <span id="CONF2017"><div class="csl-block"> my normal entry here </div></span>
</li>
```
By doing this, I could apply some style to the items in the list, e.g., differentiate the types of publication using different colors. However, I cannot find any way of doing this.

Although I saw that some attributes could be added to the `<li>` using the `bibliography_item_attributes` hash, these attributes are fixed and do not depend on the BibTeX entry (right?). 

Is there a way to add attributes from the BibTeX entry to the items tags?

**Comment by inukshuk** [comment]
`bibliography_item_attributes` is just a way to add simple modifications to the default template -- for more complex use cases, such as yours, the preferred way is to [define a custom template](https://github.com/inukshuk/jekyll-scholar#bibliography-template). The template [receives a hash](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L483) containing pretty much all the information of each field so it should be no problem to add your class there.
