### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by aytekinar** [inukshuk/jekyll-scholar#201]
### Description

I am not sure if I am doing it the right way, but I am having problems installing the theme.

### Minimal (Non-)Working Example

```fish
rm -rf .gem/ .bundle/
gem install jekyll bundler
gem update ; and gem cleanup
gem outdated
```
The above script gives nothing, meaning that I have all my `gem`s up-to-date.

Here is the configuration:
```fish
jekyll -v # <- this gives: jekyll 3.5.1
bundle -v # <- this gives Bundler version 1.15.3
```

So far so good. Now I proceed...
```fish
jekyll new myblog # installs some default stuff, minima being the theme
cd myblog
vim Gemfile # <- change gem "minima", "~> 2.0" to gem "jekyll-scholar"
# ... and also, get rid of the Windows-related tzinfo-data thing
echo "theme: jekyll-scholar" > _config.yml
bundle # <- this installs jekyll-scholar properly
bundle show citeproc-ruby # gives me the installation folder
bundle show jekyll-scholar # gives me the installation folder
bundle exec jekyll build # gives the following error:

#  Dependency Error: Yikes! It looks like you don't have citeproc-ruby or
# one of its dependencies installed. In order to use Jekyll as currently configured,
# you'll need to install this gem. The full error message from Ruby is: 'cannot load
# such file -- citeproc-ruby' If you run into trouble, you can find helpful resources
# at https://jekyllrb.com/help/! 
# jekyll 3.5.1 | Error:  citeproc-ruby

```

I am not sure if I am doing it properly, but it seems that this method works with `minima` and some other themes I have tested.

I would appreciate any help of yours. Thanks!

**Comment by inukshuk** [comment]
Jekyll-Scholar is not a theme but a Jekyll plugin -- check out this repo's readme for installation instructions.

**Comment by aytekinar** [comment]
My bad!

It works flawlessly. I will play with it --- THANKS!

Sorry for being so dumb! I thought it would be something like JemDoc, including some template/theme, too.
