### ISSUE TITLE
How to avoid extra numbers with IEEE citation style?

### ISSUE THREAD

**Issue by mabalenk** [inukshuk/jekyll-scholar#203]
Dear all, I'm using the 'ieee-with-url' citation style. Once the list of references is created, I see two numbers near each citation, e.g.:

1. [1]J. Smith, “How to Bake Bread,” Journal of Good Breadmaking, 2017.

Do you possibly know how to avoid the first number "1. "?

The settings in my configuration file are:

_config.yml:

scholar:
  style: ieee-with-url
  locale: en
  source: ./bib
  bibliography: references.bib

The list of references is obtained via the following command with a filter:

`{% bibliography --query @article %}`

**Comment by inukshuk** [comment]
Sure. The first number is not part of the rendered reference, but of the HTML list; you can adjust list styles in your site's CSS. (Also search the closed issues here to find a couple of discussions of this topic).

**Comment by Yasu31** [comment]
Just linking to the related (closed) issues for future reference...
https://github.com/inukshuk/jekyll-scholar/issues/160
https://github.com/inukshuk/jekyll-scholar/issues/340
https://github.com/inukshuk/jekyll-scholar/issues/75
