### ISSUE TITLE
bibliography table Template

### ISSUE THREAD

**Issue by tomasparks** [inukshuk/jekyll-scholar#204]
I would like to have a table template for my bibliography for I can use [tablesorter](http://tablesorter.com/docs/), but the order list tag ( <i> ) screw up the table

**Comment by inukshuk** [comment]
Set the `bibliography_list_tag` to `tbody` and the `bibliography_item_tag` to `tr`; additionally, you will have to [define your own `bibliography_template`](https://github.com/inukshuk/jekyll-scholar#bibliography-template) to create the table cells with the appropriate data.

**Comment by tomasparks** [comment]
It does not work, here are my files to help in debugging
https://github.com/tomasparks/website/blob/master/scholar.yml
https://github.com/tomasparks/website/blob/master/_layouts/bib_table.html
https://github.com/tomasparks/website/blob/master/projects/3D_papers.html

**Comment by inukshuk** [comment]
_config.yml:

```
gems:
  - 'jekyll/scholar'
scholar:
  bibliography_list_tag: tbody
  bibliography_item_tag: tr
  bibliography_template: <td>{{reference}}</td>
```

Produces:

```
<table>
  <tbody class="bibliography"><tr><td><span id="wb:passagen">Benjamin, W. (1983). <i>Das Passagen-Werk</i>. (R. Tiedemann, Ed.). Frankfurt am Main: Suhrkamp.</span></td></tr></tbody>
</table>
```

That said, with this approach you cannot easily put in other rows into the same `tbody` for that you'll have to overwrite the bibliography tag yourself I think (at least I can't think of an easy way to do this via config options only).

**Comment by tomasparks** [comment]
turns out jekyll was not reading all my config files Doh
