### ISSUE TITLE
List of references, show download PDF link

### ISSUE THREAD

**Issue by mabalenk** [inukshuk/jekyll-scholar#206]
I would like to use the file repositories feature of jekyll scholar to allow a visitor of my website to download an article in PDF, if it exists.

The relevant part of my `_config.yml` file is:

    scholar:
      style: ieee-with-url
      locale: en
      source: ./assets/pub
      bibliography: references.bib
      repository: ./assets/pub

An example of the BibTeX entry for the article I would like to make available in PDF format:

    @INPROCEEDINGS{Smith07,
      author    = {John Smith},
      title     = {How to Be a Gentleman},
      year      = {2007},
      month     = oct # { 20--23,}
    }

The PDF file called `Smith07.pdf` is located under the `./assets/pub` directory. However, the link to the PDF file is not generated automatically. Please let me know, if I missed out something. Maybe it is necessary to modify the `ieee-with-url` style file? Thank you.

**Comment by inukshuk** [comment]
Have you looked at the example in the [readme](https://github.com/inukshuk/jekyll-scholar#file-repositories)? To actually show the links you need to put them in you [reference template](https://github.com/inukshuk/jekyll-scholar#bibliography-template): i.e., if you want to show the link to the PDF after the reference, your template could be `{{ reference }} [<a href="{{links.zip}}">PDF</a>]``

**Comment by mabalenk** [comment]
Thank you for your answer. I don't use `{{ reference }}` explicitly. My lists of references are generated automatically with `{% bibliography --query @inproceedings %}`.

**Comment by inukshuk** [comment]
The default template is `{{reference}}` -- that is, it renders the formatted reference and nothing else. But there is more information which you could render in the template: for example, it gets passed authors, the citation number, most of the fields from your original BibTeX entry, and the links to the file repository. In other words, yes, if you want to do something with the link to the PDF (i.e., render it as a link) you need to do that in the template.

For simple templates, you can put it completely into your `_config.yml` as a string. For more complex templates, you would put the template into a separate file. Your error above looks like there is a problem with the YAML file (likely just a syntax problem). You can take a look our [test cases](https://github.com/inukshuk/jekyll-scholar/blob/master/features/repository.feature#L7) for some examples.

**Comment by mabalenk** [comment]
Thank you for your help. I have succeeded using your examples.

I have another related question. Is it possible to selectively specify the link to the PDF file, if it exists, and use the standard template if the file is not available in the repository? So far my solution looks this way. But it isn't working.

    ---
    ---
    {% assign lnk = {{ link }} %}
    {% if lnk != ""  %}
      {{ reference }} <a href="{{ link }}"><i class="fa fa-download" aria-hidden="true"></i> (pdf)</a>
    {% else %}
      {{ reference }}
    {% endif %}

**Comment by inukshuk** [comment]
Why do you need to re-assign link here? Can't you test the `link` variable directly?

**Comment by mabalenk** [comment]
Once I test for the `{{ link }}` variable directly as:

    {% if {{ link }} != ""  %}

I obtain the following error:

    Liquid error: Unknown operator link

**Comment by inukshuk** [comment]
What about `{% if link %}` though?

**Comment by mabalenk** [comment]
Perfect! It works! The solution was much simpler, than I thought. Thank you.
