### ISSUE TITLE
Enhance authors

### ISSUE THREAD

**Issue by kellertuer** [inukshuk/jekyll-scholar#207]
I just started working with jekyll and jekyll-scholar and at first sight that all looks awesome and seems the way I want to go with my bibtex references.

I would like to enhance (kind of) each author with a link, i.e. let's say I have a seperate list (in `names.yml`say, something like

authors:
    `John Doe`:
      url: http://johndoe.com
      info: 'some info'

That I already use throughout my page (something like `authors['John Doe'].url` to refer to this authors profile page at his university (or some other further information).

What I would like to do is for any author appearing in my references named `John Doe` (I am using `John Doe and Jane Doe` in my bibfile not the comma separated one or such, and always with full name) to replace the displayed author `Doe, J.` with something linking to his page, i.e. `<a href="{{ authors['John Doe'].url }}">Doe, J.</a>`. Is something like that possible with jekyll-scholar? Or more general, is it possible to have spans around also the Journal and such, so that I can change style with CSS?

Well and of course if the above is possible, it is easy to enhance that by only using liks where the author is present in the mentioned `names.yml` – but that's just further small stuff ;)

Any hint would be awesome on how to include ruby into the style of the references (and get access to the nonshortened name).

Bests,
Ronny

**Comment by kellertuer** [comment]
Thanks for the answer. Yes I worked a little on an own style of my references (basically adding an abstract that can be toggled visible and such) and also saw that the `entry` provides access to all fields from BibTeX, which is nice, though I have not completely understood which fields are excluded from be `{{entry.bibtex}}`, abstract seems to be excluded but other non-bibtex fields stay in (like `link` if you specify such a field).

And from you two approaches I really like the hooks idea, because I also miss `<span>`s for the title or the journal to add formating to these parts of the rendered reference with CSS.

For the first approach, i.e. working on an own layout using the custom template, I would miss that I can only change the style by changing the layout (though that might be what I'll try next), so the hooks/injections might be better if you still want to be able to use CSLs, but I haven't looked ad citeproc-ruby yet.

**Comment by inukshuk** [comment]
Yes, hooks would be nice, but we'd have to implement them in citeproc-ruby first.

You can already change the CSL style if you want to add spans around the title for example. Just copy the CSL you're using and make adjustments, then tell jekyll-scholar to use your style.

There are a few configuration options which determine which BibTeX fields should be included or skipped (would need to search the issues now, but I remember there were issues with including, e.g., abstracts, in some situations).

**Comment by inukshuk** [comment]
Arbitrary hooks are tracked by #45 already. Closing this one.
