### ISSUE TITLE
Access file using front matter 

### ISSUE THREAD

**Issue by Stelios3g** [inukshuk/jekyll-scholar#210]
Hey @inukshuk , I was wondering if there is a way to access a file like this {% bibliography --file {{ fname }} %} where fname is my file name and has been previously assigned.

**Comment by inukshuk** [comment]
I think we currently interpolate only the `query` parameter. Would be an easy PR to interpolate `file` as well though, if you'd want to give it a try.

**Comment by Stelios3g** [comment]
Alright,i m not experienced in ruby and gems,but i would like to give it a try.

**Comment by inukshuk** [comment]
I'd start by adding `interpolate(file)` [here](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L47).

**Comment by Stelios3g** [comment]
So, i add to code this : `def query
        interpolate @query
      end `, now i  think i have to go there : `opts.on('-f', '--file FILE') do |file|
            @bibtex_files ||= []
            @bibtex_files << file
          end` and make some changes right ?

**Comment by inukshuk** [comment]
I think you want to change [line 47](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L47) to be:

```Ruby
@bibtex_files << interpolate(file)
```

**Comment by Stelios3g** [comment]
Hmm,done.Do we have to add there : `def entries
        sort bibliography[query || config['query']].select { |x| x.instance_of? BibTeX::Entry}
      end` this : `sort bibliography[file || config['file']].select { |x| x.instance_of? BibTeX::Entry}` ? (according too how query works).Furthermore,after this we have to make more changes in other files like bibliography.rb or not ?

P.M(Sorry for all this silly questions,but all this time i was scratching the surface with jekyll themes and jekyll-scholar and didnt get in depth with gems and ruby etc.Hope this is a good chance to start "play" with gems.Thanks you for mentoring me!)

**Comment by inukshuk** [comment]
Everyone starts somewhere 👍 

Doesn't the one line change above already do what you need? You certainly don't need to change the `entries` helper.

**Comment by Stelios3g** [comment]
Thanks,
Let me do some tests and i will give you feedback .I think we are ok with this change,but i want to check it again.If all goes well i will PR!

**Comment by Stelios3g** [comment]
I m trying to use --file but i dont know if it is correct.Before interpolate the --file,i was using it with the name of scholar.(example --file scholarname).Now i m trying to put instead of scholarname a liquid assigned variable.How would that format be  ? (i m trying it with differnet ways and cant compile cause of errors)
Plus: I found a file -defaults.rb- .Maybe we should define a format there ?

**Comment by rseac** [comment]
@Stelios3g I wonder if recent commits (#218) address this issue?

**Comment by Stelios3g** [comment]
@rseac I have the same problem again ,but maybe its my fault(liquid code!!!).Nevermind,thanks to both of you!
