### ISSUE TITLE
A strange issue with bibtex compiling: "Lexer: unexpected token"

### ISSUE THREAD

**Issue by i2000s** [inukshuk/jekyll-scholar#212]
Dear jekyll-scholar developer,

I am using jekyll-scholar on my Jekyll website, but it gives me a bunch of warnings when I compile the markdown pages with citations to generate the static pages. The warnings can be found [here](https://travis-ci.org/i2000s/en) at the end. For example, one line is 
```
W, [2017-12-04 07:37:18#19849]  WARN -- : Lexer: unexpected token `'' at 34355; brace level 1; mode :entry.
```
Other lines are similar. It only occurs after I started to use a long bibtex file. The bibtex database can be found [here](https://github.com/i2000s/Archive). The page I think that generates these warnings may be [this one](https://github.com/i2000s/en/blob/dev/assets/files/research-statement.md) in my github repo. 

I didn't find any hints after my online search. Hopefully, you can give me some insight. 

Thanks,

Qi

**Comment by inukshuk** [comment]
On line 814 there is a key with a `'` which bibtex-ruby does not accept as a valid key (did not check the rest of the file, but in line 828 there is a similar key with a `\`` that might cause problems).

**Comment by i2000s** [comment]
Excellent! For those who encountered similar warnings, I fixed the errors by opening the bibtex file with Vim, typing `:goto NUM` to go to the corresponding `NUM'th character given by the warning messages, and fixing the wrong bibtex keys with special characters. 

Thanks.
