### ISSUE TITLE
Details links are broken with some custom permalink settings

### ISSUE THREAD

**Issue by alzeih** [inukshuk/jekyll-scholar#227]
In `def details_file_for(entry)`  

```ruby
      def details_file_for(entry)
        name = entry.key.to_s.dup

        name.gsub!(/[:\s]+/, '_')

        if site.config['permalink'] == 'pretty'
          name << '/'
        else
          name << '.html'
        end
      end
```
( from https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L553-L563 )

This doesn't work with custom permalink styles that are similar to pretty, but not called `pretty`.

e.g: `permalink: /:year/:month/:day/:title/` in `_config.yml` will generate a Details link to `/bibliography/ruby.html` but the page is at `/bibliography/ruby/` and the file at `_site/bibliography/ruby/index.html`

This seems related to #113 .

**Comment by alzeih** [comment]
If it's not feasible to use the site wide permalink style, maybe the permalink style for details pages could be a new configuration option for `jekyll-scholar` (`details_permalink` ?) with a nil default, and if it is set, use that instead of the site's permalink setting?

**Comment by inukshuk** [comment]
We could probably just add the forward slash if the permalink setting ends in a slash? Do you think that would work? I haven't used Jekyll in a while so I'm not up to speed with what settings are common.

**Comment by alzeih** [comment]
@inukshuk sounds good to me. I've submitted a PR for this.
