### ISSUE TITLE
Dependency Error: "cannot load such file -- unicode_utils"

### ISSUE THREAD

**Issue by fniephaus** [inukshuk/jekyll-scholar#228]
> Dependency Error: Yikes! It looks like you don't have jekyll/scholar or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- unicode_utils' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!

This happens with the latest version (5.11.0).

**Comment by fniephaus** [comment]
I've been using Ruby 2.1, with 2.3 everything seems to work...

**Comment by inukshuk** [comment]
`UnicodeUtils` has not been used by jekyll-scholar for a long time (it was used by citeproc-ruby a while ago for older Ruby versions). Are you using an old version of Ruby or outdated Gems maybe?

**Comment by inukshuk** [comment]
Ah, OK, yes, I can imagine one of the Gems trying to use unicode_utils on Ruby 2.1. You can probably fix it by adding `unicode_utils` to your Gemfile -- but better to use a newer version of Ruby; 2.1 has reached its end of life.

**Comment by fniephaus** [comment]
Thanks, good to know!
