### ISSUE TITLE
Extras: Download links

### ISSUE THREAD

**Issue by ghost** [inukshuk/jekyll-scholar#23]
In my bibtex file I have special fields to indicate the names of files for presentations and papers.  This is picked up by bibliography tag, and HTML with the link is rendered.  There is an additional field to make the reference public or not.  For example:

``` bibtex
@book{python,
  author={M. Lutz},
  year={2001},
  title={Programming Python, Second Edition},
  publisher={O'Reilly Media, Inc.},
  address={Sebastopol, CA},
  pages={1026},
  pdflink1={./hello/python.pdf},
  slides={./hello/slides.pdf},
  public={yes},
  isbn={0596000855}
}
```

Has pdflink1, slides, and public.  If the public is yes then the reference is generated with download links to the paper, and presentation.  Associating the download field with the rendered HTML is also done using configuration parameters.  For example, pdflink1 renders as paper, and slides and presentation.  Example: https://ece.uwaterloo.ca/~hdpatel/uwhtml/publications/index_bytype.html

**Comment by mattgilbertnet** [comment]
When I try a csl tweak like @ashinkarov 's above:

> ```
> <macro name="urlaccess">
>     <choose>
>       <if variable="URL">
>           <text variable="URL"
>                 prefix="&lt;a style='margin-right:20px' href=&#34;" 
>                 suffix="&#34;&gt;[url]&lt;/a&gt;"/> 
>       </if>
>     </choose>
>   </macro>
> ```

Then add `<text macro="urlaccess" prefix=" "/>`to the csl's bibliography tag, bibliography outputs characters like `&lt;` directly, rather than `<`. So, the html isn't rendered correctly. How did @ashinkarov get this to work?

**Comment by ashinkarov** [comment]
Here is a link to my csl file:

https://github.com/ashinkarov/ashinkarov.github.com/blob/37b020067def1c2b75ffc56601558c0c1e412002/plugins/ieee.csl#L180

I don't think I use any other tricks.  My bib file contains a field called URL for every entry, and then in _config.yml you say:

https://github.com/ashinkarov/ashinkarov.github.com/blob/37b020067def1c2b75ffc56601558c0c1e412002/_config.yml#L107
