### ISSUE TITLE
Different csl files for different pages or lists?

### ISSUE THREAD

**Issue by mattgilbertnet** [inukshuk/jekyll-scholar#244]
Is it possible to specify a different csl file to use for different pages? I'm working on a site that has academic bibliographies and lists of popular press coverage that should follow different formatting rules. Can the global csl file specified in _config.yml be overridden somehow?

**Comment by inukshuk** [comment]
You can override the default style using the `--style` parameter of the `bibliography` or `cite` commands.

It would be great to add per-page overrides to the defaults (defined in each pages frontmatter) as outlined in [this thread](https://github.com/inukshuk/jekyll-scholar/issues/95).

**Comment by mattgilbertnet** [comment]
Aha! Sorry I overlooked this. Thank you!
