### ISSUE TITLE
Extras: Bibliography ordered By year, By Type, By Author

### ISSUE THREAD

**Issue by ghost** [inukshuk/jekyll-scholar#25]
I believe scholar already has these features through query (maybe not author).  However, I find that having special tags or parameters to go along with the bibliography to generate a bibliography ordered by year, bibliography ordered by type, and bibliography ordered by year/type for an author is useful.  

Once again, I understand that some of these can be implemented with a combination of existing query features and HTML, which we could just provide alternatively.

**Comment by inukshuk** [comment]
See #121
