### ISSUE TITLE
New entry type

### ISSUE THREAD

**Issue by boknilev** [inukshuk/jekyll-scholar#250]
Is it possible to define a new entry type to use when grouping by type? 

Example use case: 
The bibliography contains conference papers and workshop papers, both currently with `inproceedings` type. There is no proper type for workshop papers, but they behave the same as conference papers in bibtex (i.e., `inproceedings` type). However, when grouping by type, I would like them to be in two separate groups. Can this be achieved?

**Comment by inukshuk** [comment]
Well, you'll have to differentiate the two groups in your bibliography somehow. If you give them two different types and group by type in Jekyll-Scholar they will be rendered in two different groups (I don't think Jekyll-Scholar objects if you use something that's not a known type in BibTeX).
