### ISSUE TITLE
change the type name (header) size

### ISSUE THREAD

**Issue by zhiyzuo** [inukshuk/jekyll-scholar#252]
First, thank you for this great tool!

I wonder if there's any way to adjust the size of the headers (or type names) of citation groups. I am putting the bibliography list with my other sections and want to make the header sizes smaller.

Thank you!

**Comment by inukshuk** [comment]
There is a `bibliography_class` config option which is used for the group headers if I'm not mistaken.

**Comment by zhiyzuo** [comment]
I saw at [defaults.rb](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/defaults.rb) but not sure how it should be used to change font size. The default is `'bibliography_class' => 'bibliography'` - how does it work? Can you elaborate a little bit more?

Thank you!

**Comment by inukshuk** [comment]
Well, if you take a look at the generated HTML the heading should all be in `h2.bibliography` tags or something like that. You should style them in your stylesheet -- jekyll-scholar does not really add any styles except those mandated by the citation styles.

**Comment by zhiyzuo** [comment]
Found it! Thank you!
