### ISSUE TITLE
Add a custom class for the citation references?

### ISSUE THREAD

**Issue by antoinentl** [inukshuk/jekyll-scholar#258]
is it possible to add a (custom) class for the citation references (in the text)?

Example: `<a href="#simondon_du_2012" class="bibliography">(Simondon, 2012)</a>`

I find the way to custom the template for the bibliography (and it's pretty cool), but not for the citations.

**Comment by inukshuk** [comment]
There's currently no way to do that, no. But it's a good idea and should be very easy to do by adding something like `config['cite_class']` or something similar at the end [here](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L659)

**Comment by antoinentl** [comment]
Can you check this [PR](https://github.com/inukshuk/jekyll-scholar/pull/259)? (And thanks to @oncletom for the help!)

**Comment by inukshuk** [comment]
Looks good, thanks for contributing!

**Comment by antoinentl** [comment]
Tested and approved! Thanks for your reactivity! (And for your awesome work, this plugin rocks!)
