### ISSUE TITLE
Query by decade.

### ISSUE THREAD

**Issue by HaoZeke** [inukshuk/jekyll-scholar#278]
First off, great plugin! I have noticed that I am not able to use multiple filters on the same key in my query. Specifically, I have been trying variations on the following:

```
{% assign dec1 = 2019 %}
{% assign dec2 = 2009 %}
{% bibliography --query @inproceedings[year<={{ dec1 }} && year>{{dec2}}] %}
```

However, this does not seem to be supported at the moment. Is there any work-flow to allow me to get a query containing the publications of multiple years?

**Comment by inukshuk** [comment]
It's too distant for to remember if there was a specific reason for this, but it seems like only `<=` and `>=` are valid query operators. Your query should work if you use `year >= {{dec2}}` and set dec2  to 2010.

**Comment by HaoZeke** [comment]
Actually it's not just the operators, I can't seem to chain queries with `&&` on the same key.

Eg. `year && author` work together but not year and year.

**Comment by inukshuk** [comment]
I don't think so? [This example works](https://github.com/inukshuk/jekyll-scholar/commit/e3e058450ba1759234e8cbbf3d5db4047fd4aeb0).

**Comment by HaoZeke** [comment]
Oh, thanks. I probably missed something.


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=10.0.23&pv=9&source=email_footer_2] On Fri, Sep 13, 2019 at 2:01pm, Sylvester Keil < notifications@github.com [notifications@github.com] > wrote:
I don't think so? This example works [https://github.com/inukshuk/jekyll-scholar/commit/e3e058450ba1759234e8cbbf3d5db4047fd4aeb0] .
