### ISSUE TITLE
`details_link_for` not respecting `base` anymore

### ISSUE THREAD

**Issue by ph03** [inukshuk/jekyll-scholar#284]
With fe5a875 `def details_link_for(entry, base = base_url)` is not respecting the second `base` parameter anymore, resulting in wrong links if not empty

cc @bronsonp

**Comment by bronsonp** [comment]
@ph03 You are asking for the base parameter to be prepended to the URL for bibliography detail pages?

Would this fix this issue?
https://github.com/bronsonp/jekyll-scholar/commit/97c7828ea88a0a07d16cd8f3d53b57d363ffacbd

**Comment by ph03** [comment]
Yes, exactly, I think that should fix it - note that before fe5a875 the base was prepended in a similar way:

![image](https://user-images.githubusercontent.com/390527/68123240-bac9f980-ff0c-11e9-8c01-2983cebfac3b.png)

**Comment by bronsonp** [comment]
OK, I will put in a pull request.

**Comment by inukshuk** [comment]
Thanks! The fix landed in 6.3.3.

**Comment by ph03** [comment]
awesome, thanks guys!
