### ISSUE TITLE
baseurl breaks details pages

### ISSUE THREAD

**Issue by tim-taylor** [inukshuk/jekyll-scholar#298]
If `baseurl` is set to a non-root path in `_config.yml`, the generated details pages for each paper are placed in the incorrect location within the `_site` folder.

For example, if `baseurl` is set to `/xyz` and `details_dir` is set to `details` the details pages are placed in the folder `_site/xyz/details/`. They should instead be placed in `_site/details/`, because the entire contents of the `_site` folder is to copied to the `xyz` directory on the server.

The generated details link for each bib item points to `https://mydomain.com/xyz/details/paperkey.html` (which is where the page _should_ be), but this link is broken because the page is actually at `https://mydomain.com/xyz/xyz/details/paperkey.html` (note the repeated `xyz`). 

The file repository links also have `/xyz` prepended to them.  For example, if `repository` is set to `repo` then `links.pdf` for a paper looks like `/xyz/repo/paperkey.pdf`. This means that `{{ links.pdf | absolute_url }}` gives `https://mydomain.com/xyz/xyz/repo/paperkey.pdf` (again, note the repeated `xyz`).

**Comment by tim-taylor** [comment]
This might be related to the fix that was made for #284 ?

**Comment by inukshuk** [comment]
Yeah, looking at #285 there is even a test case explicitly testing that the base directory is created in the site root. That's odd, will be fixed soon.
