### ISSUE TITLE
Query for entries that do NOT have a field

### ISSUE THREAD

**Issue by haji-ali** [inukshuk/jekyll-scholar#302]
In the README file, the following query

```
query: "@*[url]"
```

includes all entries with a url field. So I thought that

```
query: "@*[!url]"
```

would includes all entries _without_ a url field, but that's not working for me. Is this not the correct syntax?

**Comment by inukshuk** [comment]
You can probably solve this by using `!~` -- this returns true if the attribute value is nil or if the pattern does not match. Maybe try `@*[url !~ .]` or something similar.

**Comment by haji-ali** [comment]
Yep, that worked. Thanks.
