### ISSUE TITLE
 Liquid Exception: failed to extract CSL data from "mla"

### ISSUE THREAD

**Issue by drscotthawley** [inukshuk/jekyll-scholar#307]
Hi, I'm taking on the project of trying to integrate jekyll-scholar and Fastpages.  

I have ` style: mla` in my `_config.yml` file as in the documentation, but when I run the build, I hit the following:  

```
 Liquid Exception: failed to extract CSL data from "mla": No such file or directory @ rb_sysopen - mla in /data/_posts/2020-07-01-Citations-Via-Bibtex.md jekyll_1     | /usr/local/bundle/ruby/2.6.0/gems/csl-1.5.1/lib/csl/loader.rb:90:in `rescue in extract_data_from': failed to extract CSL data from "mla": No such file or directory @ rb_sysopen - mla (CSL::ParseError)
```

Any suggestion on what to do about this?    

Since I know I'll be asked:
```$ bundle info jekyll-scholar
  * jekyll-scholar (6.8.0)
	Summary: Jekyll extensions for the academic blogger.
	Homepage: http://github.com/inukshuk/jekyll-scholar
	Path: /var/lib/gems/2.7.0/gems/jekyll-scholar-6.8.0
```

In case this helps provide more info/context:

BTW, I have jekyll-scholar enabled probably three different ways currently.  `sudo gem install` didn't seem to do the sufficient work, adding the `requires` to an extra file in the `_plugins` directory, editing the Gemfile, and adding `gem` command in the config file.  Running `bundle install` after all that seemed to have done the trick. 

Doing all of those things seemed to be necessary just to get it to stop complaining about an unknown `{% bibliography %}` tag and get me to the point where I could start seeing errors about the bibliography itself, e.g. the fact that jekyll-scholar seems to crash on any `url =` tags in the BibTex file. :-(   Saying goodbye to my urls is what got me to the present error.

**Comment by inukshuk** [comment]
That's likely a mistake in the README (or maybe the styles were renamed in the meantime). Currently, these MLA styles are available:

* modern-language-association-6th-edition-note
* modern-language-association-7th-edition
* modern-language-association-7th-edition-underline
* modern-language-association-7th-edition-with-url
* modern-language-association

You can see all available styles  if you check the contents of the `csl-styles` Gem (in `vendor/styles`).

**Comment by drscotthawley** [comment]
Ok, thank you for the clarification!   I also see the list posted in the [csl-styles repository](https://github.com/hugoroy/csl-styles).   An update to the README would fix this Issue.
