### ISSUE TITLE
problem of cite style

### ISSUE THREAD

**Issue by fdq09eca** [inukshuk/jekyll-scholar#311]
I am very new to this plugin and Jekyll, forgive me if I am asking something stupid.
I understand that `{% cite ruby %}` renders `(Flanagan & Matsumoto, 2008)` as a format of `(authors, year)`.
How can I also render it as `authors (year)` i.e. `Flanagan & Matsumoto (2008)`

**Comment by inukshuk** [comment]
You can pick [any available CSL style](https://www.zotero.org/styles/) that fits your requirements.

If you're looking for narrative citations, they are currently not supported directly, but there are many possible workarounds (see #238; how feasible depends on your use case).
