### ISSUE TITLE
Citation tags not rendering 

### ISSUE THREAD

**Issue by wysiwyggins** [inukshuk/jekyll-scholar#312]
This may be related to a previous issue- https://github.com/inukshuk/jekyll-scholar/issues/237

Citation tags such as {% cite foo %} and {% quote foo %} do not render to html on my site when built (they just appear as the raw liquid tag), however they are correctly populating the  {% bibliography --cited %} bibliography for the page, so they are presumably being read. Other markdown like links and emphasis are being rendered on the page.

if it's relevant, the  {% bibliography --cited %} is part of this page's layout file, so the unrendered citations are happening in the {{ page.content }}, like the previous issue linked. 

in my config.yml scholar is left to defaults except for 
```
scholar:
  style: modern-language-association
```
no build errors.

**Comment by inukshuk** [comment]
Are other liquid tags processed normally and only cite/quote come through verbatim?

**Comment by wysiwyggins** [comment]
Hmm, looks like the problem is on my end, it won't take any {% %} tag in this content but it's still rendering the regular markdown.

**Comment by wysiwyggins** [comment]
I found the problem- be sure to use {{ content }} in the layout, not {{ page.content }}
