### ISSUE TITLE
Change the default bibliography for each post

### ISSUE THREAD

**Issue by nicofranzp** [inukshuk/jekyll-scholar#318]
Hi all, 
I have a bunch of contributors that share a common folder structure to write papers and would like to keep it when writing posts in a website --- this implies that we cannot keep a centralized bibliography. What we would normally do is to have a `\src` folder for each post with the bibliography in it. Then in the from matter of the post we wold set `bibliography: "../_posts/Post Folder/bibliography.bib" ` and then each time we cite something `{% cite citeTag --file {{page.bibliography}} %}`. Is there any way to do that only writing `{% cite citeTag %}`? or even better \cite{citeTag} ?

**Comment by inukshuk** [comment]
We already added per-page config overrides in the front matter some time ago; unless there's something special about the bibliography source setting that currently eludes me, this might be possible:

```
---
scholar:
  bibliography: "..."
---
```

**Comment by nicofranzp** [comment]
Cool... Thank you very much, this is exactly what I was looking for! Didn't find it in the documentation though.
