### ISSUE TITLE
"et al" not ideal for web

### ISSUE THREAD

**Issue by gkthiruvathukal** [inukshuk/jekyll-scholar#320]
There seems to be an option to suppress authors from being listed, but is there an option to include authors in a citation?

Let me try to motivate the problem.

It seems like for any entry having greater than 2 authors, the default is to use _et al_.  For including your own publications on your own web pages, you'd like your own name to show up in the citation. Being someone with a name at the end of the alphabet, my name often appears last and thereby relegated to the _et al_.

Given that the target of this effort is academic--and probably more focused on science/engineering/computer science academics--I'd like to encourage that you heed the NSF's advice on the use of _et al_, which strongly discourages the use of it for less than 10 authors, as shown in this guidance at https://researchdevelopment.vpr.virginia.edu/NSF-references-cited:

_Do not use “et al.” in references unless the publication has an extremely large number of authors (10 or more), even if the reference style you’re using would normally call for it. NSF does check the references, and will return proposals without review if they are not formatted correctly._

I think `jekyll-scholar` is primarily targeting use in web sites (built on Jekyll) so there should be some way to set the et al threshold.  There should also be a way to include authors manually.

Perhaps there could be two options:

`--et-al-threshold <count>`
and 

`--add-author <Name>`

Is it doable?

**Comment by inukshuk** [comment]
The way *et al* is treated is governed by the CSL style. You can either pick a style that does not use et al or you can edit your preferred style, either by turning off et al entirely or adjusting the [inheritable name attributes](https://docs.citationstyles.org/en/1.0.1/specification.html#name) `et-al-min` and `et-al-use-first` of the style

**Comment by gkthiruvathukal** [comment]
Thanks, @inukshuk. I was starting to look into this. Now if I can just find the one that doesn't use et al, that will be great. You've given me what I need to know. Looks like I was using "apa" by default.

**Comment by gkthiruvathukal** [comment]
@inukshuk Just one follow up to this, can the `et-al-min` option be passed to the `{% cite`?

**Comment by inukshuk** [comment]
That's currently not possible, no. One way to achieve this is to modify the CSL style and then use the full path to the modified style file instead of the style's id in jekyll-scholar.

**Comment by gkthiruvathukal** [comment]
Thanks! For now, I've decided not to use this feature on my web site. It would be good to see an example of how to link to a custom CSL. I didn't see any docs that cover this issue. 

In any event, I think we can go ahead and mark this issue as closed, if you agree.

**Comment by inukshuk** [comment]
To use a modified style you can either alter the default style root directory (and use the style id) or simply use the full path to the style in your configuration. For example: `style: /home/user/chicago-modified.csl` in the `scholar` section of your `_config.yml` or the page's front matter, or, alternatively, using the `--style` option of the `bibliography` or `cite` tag.

**Comment by gkthiruvathukal** [comment]
Thanks, @inukshuk!
