### ISSUE TITLE
config question re details links

### ISSUE THREAD

**Issue by pazz** [inukshuk/jekyll-scholar#325]
I would like to let jekyll-scholar generate details pages but not add the "details" link after each bib entry when using the bibliography tag. I'm trying to make the title of an article the link to the details page. Is that possible?
From a quick glance at [the code](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/tags/bibliography.rb#L65) it looks like this is hard-coded, correct?

I've already tried setting these in my config file:

```yaml
details_link:
details_link_class: "hidden"
```

Thanks for this awesome piece of software :)

**Comment by inukshuk** [comment]
You're right. It looks like we just add the link if the [details page layout exists](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L595) and use the `details_link` option only to configure the name of the link. A quick way to address this, without adding extra options might be to skip the link if the option is blank?

In any case, you can use the `details_link` tag to create a link to one of the details pages anywhere.

**Comment by drmikeuk** [comment]
If you wanted to make the whole citation (not just the title) the link then you could try stretching the details link to cover the parent LI, a bit like [bootstrap does](https://getbootstrap.com/docs/5.0/helpers/stretched-link/).
