### ISSUE TITLE
Filter condition with set membership

### ISSUE THREAD

**Issue by afspies** [inukshuk/jekyll-scholar#328]
Hi, 

I am trying to use a filter query of the form

`{% bibliography --query @article[{{selected_tags}} subset of tags] %}`

where tags is a field in the bilbiography entries as `tags={tag1,tag2...}`,

Is there some convenient way of implementing this through filtering, or do I need to do this check in the bibtemplate directly to apply the tag selection?

Thank you!

Alex

**Comment by inukshuk** [comment]
Unfortunately the query language currently does not support tests for set membership. However you can use variables in query parameter, so you could construct suitable queries either using multiple tests conjoined with `||` or by creating a regular expression made up of all the selected tags.

**Comment by afspies** [comment]
Great, using `||` should suffice - Thank you! :)
