### ISSUE TITLE
Unclear how to deal with in-text citations

### ISSUE THREAD

**Issue by pierrelux** [inukshuk/jekyll-scholar#33]
Under a citation style such as APA for example, it is convenient to be able to control when parentheses must be used. I would like to say for example " Sutton, Precup & Singh (1998) proposes a model [...]" rather than producing " (Sutton, Precup & Singh, 1998) proposes a model" by the current {% cite %} mechanism.

In Latex, these cases can be handled with \parencite, \textcite under Memoir, or \citep and \citet with Natbib. 

Is there any plan to include such functionality ?

**Comment by jewellsean** [comment]
Is there any easy way to do this in the latest versions of jekyll-scholar? or, is the suggested approach still to hack the apa.cls file?

**Comment by inukshuk** [comment]
Something like LaTeX `\citet` is still not covered well by CSL, so, depending on your case I'd say either a hacked CSL style or the `--suppress-authors` options are the best solutions for the time being.
