### ISSUE TITLE
Completely disable details link generation for a page

### ISSUE THREAD

**Issue by iwishiwasaneagle** [inukshuk/jekyll-scholar#359]
Currently the only way to disable the details page for a post is by hiding it using

```
details_link:""
```

However, this still creates a href like

```
<a class="details" href="/bibliography/citation.html"></a>
```

This is terrible for SEO as it creates countless links leading to 404s. It'd be great to be able to disable this entirely.

**Comment by inukshuk** [comment]
You can set the option to `false` to skip the link (`""` the empty string is still a positive value).

**Comment by iwishiwasaneagle** [comment]
HI @inukshuk, thanks for replying. Could I then suggest a quick amendment to the docs for this feature?
