### ISSUE TITLE
Trouble running on osx mavericks : cannot load such file -- bibtex (LoadError)

### ISSUE THREAD

**Issue by stnava** [inukshuk/jekyll-scholar#39]
Hi There

Thank you for this wonderful effort.  I would love to get this working.  Am just starting with jekyllbootstrap so maybe my question is just ignorant.  

This is my jkblog:

https://github.com/stnava/stnava.github.com

I followed your instructions (sudo gem install ... ) and then added: 

cat _plugins/bib.rb 
require 'jekyll/scholar'

but when i do ( \* here is the problem \* ) 

jekyll serve

Configuration file: /Users/stnava/code/stnava.github.com/_config.yml
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bibtex (LoadError)
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-scholar-1.2.4/lib/jekyll/scholar.rb:6:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:135:in`require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:144:in`require'
    from /Users/stnava/code/stnava.github.com/_plugins/bib.rb:1:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-1.4.2/lib/jekyll/site.rb:77:in`block (2 levels) in setup'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-1.4.2/lib/jekyll/site.rb:76:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-1.4.2/lib/jekyll/site.rb:76:in`block in setup'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-1.4.2/lib/jekyll/site.rb:75:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-1.4.2/lib/jekyll/site.rb:75:in`setup'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-1.4.2/lib/jekyll/site.rb:29:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-1.4.2/lib/jekyll/commands/build.rb:5:in`new'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-1.4.2/lib/jekyll/commands/build.rb:5:in `process'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-1.4.2/bin/jekyll:97:in`block (2 levels) in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.1.5/lib/commander/command.rb:180:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.1.5/lib/commander/command.rb:180:in`call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.1.5/lib/commander/command.rb:155:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.1.5/lib/commander/runner.rb:402:in`run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.1.5/lib/commander/runner.rb:66:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.1.5/lib/commander/delegates.rb:7:in`run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.1.5/lib/commander/import.rb:10:in `block in <top (required)>'

my gem list is here:  

**\* LOCAL GEMS ***

bibtex-ruby (2.3.4)
blankslate (2.1.2.4)
CFPropertyList (2.2.0)
citeproc (0.0.9)
citeproc-ruby (0.0.6)
classifier (1.3.4)
colorator (0.1)
commander (4.1.5)
fast-stemmer (1.0.2)
fastercsv (1.5.5)
ffi (1.9.3)
highline (1.6.20)
jekyll (1.4.2)
jekyll-import (0.1.0)
jekyll-scholar (1.2.4)
kramdown (1.3.1)
latex-decode (0.1.1)
libxml-ruby (2.6.0)
liquid (2.5.4)
listen (1.3.1)
little-plugger (1.1.3)
logging (1.8.1)
maruku (0.7.0)
mini_portile (0.5.2)
multi_json (1.3.7, 1.3.5)
namae (0.8.1)
nokogiri (1.5.6)
parslet (1.5.0)
posix-spawn (0.3.8)
pygments.rb (0.5.4)
rb-fsevent (0.9.4)
rb-inotify (0.9.3)
rb-kqueue (0.2.0)
rbibtex (0.1.0)
redcarpet (2.3.0)
rubygems-update (2.2.1)
safe_yaml (0.9.7)
sqlite3 (1.3.7)
toml (0.1.0)
unicode (0.4.4)
yajl-ruby (1.1.0)

can  you see the problem here?

again - thanks for your help.

**Comment by nonsns** [comment]
(Just started with Jekyll, already debugging for this issue. A lexer should not break for non-printable characters. It does not even tell which input line it does break. Grrr)

**Comment by nonsns** [comment]
In my case, finding the non-printable characters in some 5000 lines of bibfiles (20XX.bib for different years) was as simple as:
          $ grep . 20*bib | cat -vet | grep \\^ | grep -v \\^I
