### ISSUE TITLE
bibliography --cited ordering

### ISSUE THREAD

**Issue by andriusvelykis** [inukshuk/jekyll-scholar#44]
I think the bibliography is not sorted at all if it is _cited-only_.

If I am looking correctly, the `references` variable in [`bibliography.rb`](https://github.com/inukshuk/jekyll-scholar/blob/6d8c0c64991031d93e09ea4081f074d802d299e6/lib/jekyll/scholar/tags/bibliography.rb) is [sorted initially](https://github.com/inukshuk/jekyll-scholar/blob/6d8c0c64991031d93e09ea4081f074d802d299e6/lib/jekyll/scholar/tags/bibliography.rb#l18) but afterwards gets lost when `cited_references` [is iterated on](https://github.com/inukshuk/jekyll-scholar/blob/6d8c0c64991031d93e09ea4081f074d802d299e6/lib/jekyll/scholar/tags/bibliography.rb#l21).

**Comment by i2000s** [comment]
@inukshuk I am using the `--cited_in_order` option for my citations with `{{ bibliography }}` blocks for my blog posts. It works great, but one issue I found is that if I define 
```
bibliography_list_attributes:
  reversed: 'reversed'
```
in my config file as my need to sort my own publications in the reversed chronological order, then the citations on my blog posts will be ordered in the reversed-citation order (see [example page](https://www.qixiaodong.tk/en/2016/07/23/put-everything-on-a-quantum-circuit-part-i.html#Gardiner1985Handbook)). Is it possible nowadays to use different ordering rules for different pages? I am on the same line as @andriusvelykis to request the capability to override the default template per page. 

Thanks,

Qi

**Comment by inukshuk** [comment]
That's currently tracked by issue #95. It would be great if someone had the time to pick it up, it's an easy fix that would result in a big improvement.
