### ISSUE TITLE
Add per-page configuration options

### ISSUE THREAD

**Issue by cjhoward** [inukshuk/jekyll-scholar#52]
The `cite` tag produces the output `(missing reference)` when a post is using a bibliography specified by the `--file` parameter.

    ---
    ---
    Lorem ipsum {% cite foobar1980 %}
    {% bibliography --file bibliography2 %}

Additionally passing the bibliography file to the cite tag via the `--file` parameter causes it to output the cite-key: `(foobar1980)`. It fails to format the citation according to the specified style and fails to generate a link to the bibliography entry at the bottom of the page. 

    ---
    ---
    Lorem ipsum {% cite foobar1980 --file bibliography2 %}
    {% bibliography --file bibliography2 %}

I do not have much experience with Ruby and the Jekyll-Scholar codebase, but I believe that citations are only considering the bibliography specified by `_config.yml`. A simple fix for this issue would be to allow users to specify a post-specific bibliography in the post's YAML front-matter:

    ---
    scholar:
      bibliography: bibliography2
    ----
    Lorem ipsum {% cite foobar1980 %}
    {% bibliography %}

**Comment by reitzig** [comment]
@inukshuk It seems that details pages are only generated for those entries in the "main" bibliography file. This causes dead links.

This may best be done with a tag parameters, though.

Use case: have one file for your own articles, and one (or more) for references used in posts.
Then, `{% bibliography -- details --file mystuff.bib %}` would print the bibliography with carefully crafted details pages, whereas `{% bibliography --cited --file b.bib %}` would just give a "flat" list of references.
