### ISSUE TITLE
doesn't seem to work on Mac OSX Yosemite

### ISSUE THREAD

**Issue by hugoledoux** [inukshuk/jekyll-scholar#61]
$ sudo gem install jekyll-scholar
Successfully installed jekyll-scholar-4.1.0
Parsing documentation for jekyll-scholar-4.1.0
1 gem installed
Hugos-MacBook-Pro-2:jk hugo$ irb
irb(main):001:0> require 'jekyll/scholar'
LoadError: cannot load such file -- jekyll/scholar
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in
`require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in
`rescue in require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in
`require'
from (irb):1
from /usr/bin/irb:12:in`<main>'
irb(main):002:0>

My friend has exactly the same issue on the same configuration. Any help appreciated.

**Comment by eric-tramel** [comment]
Just as an update to this issue, I am encountering the exact same issue as  @hugoledoux on Yosemite with a fresh Homebrew install of Ruby followed by a fresh installation of Jekyll. If I sudo into `irb`, as was mentioned earlier, I can require `jekyll/scholar`, but otherwise, no. 

Additionally, calling `jekyll serve` at either user or super-user level will claim to not find the gem. However,  `gem which jekyll/scholar` returns the appropriate path.

**Comment by julianheinrich** [comment]
having the same issue as @eric-tramel on Mavericks.
Is there a workaround to get it running temporarily?
@kenohori how did you chmod the Gems dir? Mine is world-readable but that doesn't work.

**Comment by kenohori** [comment]
@julianheinrich It was a rather bruce-force solution:
```
sudo chmod -R 755 /Library/Ruby/Gems/2.0.0/gems/jekyll-scholar-4.4.0
```

**Comment by julianheinrich** [comment]
Thanks @kenohori, unfortunately that didn't work for me.

**Comment by inukshuk** [comment]
@julianheinrich catching up, this is no longer an issue, right?

**Comment by julianheinrich** [comment]
@inukshuk no, I was able to solve it via the `Gemfile` as described above.

**Comment by ramirezgd** [comment]
I was not able to solve it using the Gemfile, nor it is a permissions problem. I've also tried all posibilities for requiring the gem. I don't know what else to do. Could anybody help, please?

FYI, I am using jekyll-scholar on El Capitan. Ruby is installed using rbenv.

**Comment by inukshuk** [comment]
@ramirezgd it would be helpful to post your Gemfile and what exactly you're trying to do that results in an error.

**Comment by ramirezgd** [comment]
Thanks for a fast response.

I am using [Indigo](https://github.com/sergiokopplin/indigo). My gem file looks like this

```
source 'http://rubygems.org'

gem 'github-pages'
gem 'rake'
gem 'rouge'
gem 'pygments.rb'
gem 'jekyll'
gem 'html-proofer'
gem 'jekyll-seo-tag'
gem 'jekyll-email-protect'
gem 'jekyll-scholar'
```

and I install them using `bundle install` The part of my _config.yml file where jekyll-scholar appears is

```
gems:
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-scholar
```

and when I execute `gulp` I get the error: `LoadError: cannot load such file -- jekyll/scholar`

P.S.: I also tried other configurations like `jekyll/scholar` but didn't work. Although the error was different

**Comment by inukshuk** [comment]
OK you should definitely put `jekyll/scholar` in the config file (the Gemfile is fine as is). And since we can't really debug your `gulp` tasks here, please just run:

 ```
$ bundle show jekyll-scholar
$ bundle exec jekyll build
```

**Comment by ramirezgd** [comment]
```
bundle show jekyll-scholar
/Users/ramirezgd/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-scholar-5.8.1
```
```
bundle exec jekyll build
Configuration file: none
            Source: /Users/ramirezgd/Documents/Repositories/webpage/_site
       Destination: /Users/ramirezgd/Documents/Repositories/webpage/_site/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.097 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

Do you want me to attach any file?

**Comment by inukshuk** [comment]
You should run this in `/Users/ramirezgd/Documents/Repositories/webpage` obviously (not in the `_site` folder).

**Comment by ramirezgd** [comment]
My fault. 

```
Configuration file: /Users/ramirezgd/Documents/Repositories/webpage/_config.yml
            Source: /Users/ramirezgd/Documents/Repositories/webpage
       Destination: /Users/ramirezgd/Documents/Repositories/webpage/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 1.068 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

Now I run `gulp` and it works. Thank you very much and apologies for incompetence. I tried `gems: ['jekyll/scholar']` but did not occur to me to just change `-` by `/` in my current configuration.

Thanks!!!!

**Comment by denisdobras** [comment]
Hello guys,

I'm very new to all of this as I'm learning to code on DevTips channel. I went through all of your comments and I still can't fix the issue.

I have a problem if I try to **jekyll serve**. Terminal returns this:

_/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.2.0/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.2.0/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'_

Your help is much appreciated!
