### ISSUE TITLE
Use jekyll-scholar for github pages

### ISSUE THREAD

**Issue by nicolasbock** [inukshuk/jekyll-scholar#67]
Hi,

can I use this plugin for webpages hosted by github pages?

Thanks already,

nick

**Comment by Eflores89** [comment]
@nicolasbock Coming late to the conversation, but how did you manage?

**Comment by nicolasbock** [comment]
@Eflores89 I build the webpage now locally and push the html only. That works great. So no server side jekyll processing required anymore.
