### ISSUE TITLE
sorting with year and month

### ISSUE THREAD

**Issue by arademaker** [inukshuk/jekyll-scholar#72]
The output ordering is wrong when I put in the config:

```
  sort_by: year, month
  order: reverse
```

How to sort by year and month decreasing?

**Comment by inukshuk** [comment]
Just added support for this. BibTeX-Ruby now returns numeric values as Fixnums and Jekyll-Scholar automatically uses month_numeric instead of month, so sorting by year and month should be supported now.

Will push this to rubygems.org later today.
