### ISSUE TITLE
year and month sort

### ISSUE THREAD

**Issue by andrewning** [inukshuk/jekyll-scholar#74]
Looking through the code it looks like multiple sort keys are allowed.  However, when I try using
``sort_by: year, month``
it doesn't behave as expected (even if month was alphabetical).

Also looking through closed issues it appears as if there was going to be a month_numeric key added, but if there was it doesn't work for me.  Is there a way to sort by year, then by month?

**Comment by inukshuk** [comment]
You're absolutely right, we haven't added support for this yet -- been too busy lately -- but this will hopefully be ready in the next release.

**Comment by inukshuk** [comment]
Sorting by year and month should be working now. Will push this to rubygems.org later today.

**Comment by andrewning** [comment]
Awesome!  Thanks.
