### ISSUE TITLE
double numbers

### ISSUE THREAD

**Issue by andrewning** [inukshuk/jekyll-scholar#75]
For some cite styles (like ieee, or american-society-of-mechanical-engineers or american-institute-of-aeronautics-and-astronautics)
I get 2 numbers for each entry in the publication list.
``1. [1]author ...``
``2. [2]author...``
and so on.  The first number is just an ordered list entry, but the second is in the actual reference text.  Is there a way I can get rid of the second number?

**Comment by inukshuk** [comment]
You can either use the configuration option `bibliography_list_tag` to something other than `ol` (note that if you set it to something other than a list, like a `div` you should also adjust the `bibliography_item_tag` option because it defaults to `li`).

My preference, however, would be to adjust your CSS using `list-style: none` to hide the HTML numbers.

**Comment by andrewning** [comment]
Yes those options would work, but I was kind of hoping for an option going the other way. I'd like to leave the list because that makes it easy to style through CSS. I was hoping to find a way to get rid of the second number that is actually in the text itself. For now I just decided to use a different reference style so it's not a big deal.

**Comment by inukshuk** [comment]
The second number is part of the rendered citation thus it is fully determined by the CSL style. Instead of using a different style you can also modify your style and remove the nodes which render the number.

**Comment by emichael** [comment]
I was having the same issue and only found out about the `bibliography_list_tag` option after googling finding this issue. Is there any page which details all of the config options?

**Comment by emichael** [comment]
Nevermind, found `defaults.rb`. Perhaps this file could be commented and pointed to in the README? That's probably the easiest way to keep the documentation up to date.

**Comment by JoostvanPinxten** [comment]
Sounds good to me! Can you initiate a pull request, so we can get started adding more info?

**Comment by scimedic** [comment]
Hi
I was able to get around this in css using 

`ol.bibliography li {
  list-style: none
}`

However, wouldn't it be easier just to incorporate this into the default.rb file since it will only affect the bibliography ol>li?

**Comment by drscotthawley** [comment]
@scimedic  Where do we add said CSS?   I don't see any mention of CSS in the README.

**Comment by RuizSerra** [comment]
I've found that a nice way to solve this is by using [`jekyll-regex-replace`](https://github.com/joshdavenport/jekyll-regex-replace).

**_layouts/bib.html:**
```html
---
---

<p>{{reference | regex_replace_once: '\d+?\.\s', ''}}</p>
```

**_config.yml:**
```yaml
# ...
scholar:
    style: wireless-communications-and-mobile-computing
    bibliography: library.bib
    bibliography_template: bib
    replace_strings: true
    query: "@*"
```

**Comment by inukshuk** [comment]
You can just [set `list-style: none`](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style) for the ordered lists used by bibliography.

**Comment by RuizSerra** [comment]
Thanks for the suggestion, @inukshuk, however it is best to leave the html list numbers for typesetting purposes (mainly so that the paragraph indents are neat). :)
