### ISSUE TITLE
hide certain bibtex fields

### ISSUE THREAD

**Issue by andrewning** [inukshuk/jekyll-scholar#78]
Is there a way to hide certain bibtex fields when displaying the bibtex in {{entry.bibtex}}?  That would be fantastic.  Currently, I preprocess my bibtex data to remove non-standard bibtex elements put in by BibDesk (like Date-Added).  However, there are others fields I would like to hide but don't want to remove from jekyll-scholar processing.  For example, "keywords" I use to filter my bibliography, but I don't really want to show the keywords.  "month_numeric" is now used for the sort and is great, but I also don't want that to show in the bibtex display.

**Comment by inukshuk** [comment]
Good point.

We actually already filter out abstracts here: https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L281 -- it would be great to instead keep a list of fields to ignore.

**Comment by andrewning** [comment]
nice.  I added a few of my own next to the abstract for now.  a user-configurable list of fields to ignore would be great.

**Comment by inukshuk** [comment]
I added the option `bibtex_skip_fields` in version 4.3.0. By default, it is set to `[:abstract, :month_numeric]`.

**Comment by andrewning** [comment]
this is great.  thanks!

**Comment by matteofrigo** [comment]
Is it possible to hide bibtex fields when we call `{% bibliography %}` ? My objective is to be able to do something like
```
{% bibliography --cited --skip-field abstract %}
```
And get the papers I cited in the page listed without the abstract field.

**Comment by inukshuk** [comment]
I'm not sure what you mean? Doesn't the `bibtext_skip_fields` allow to just this?

**Comment by matteofrigo** [comment]
No. I've tried `{% bibliography --cited --bibtext_skip_fields abstract %}` but the abstract is still there.

**Comment by matteofrigo** [comment]
Should I provide some version number to debug this?

**Comment by inukshuk** [comment]
This is not a parameter you can pass to the tag, but one that you add to your `_config.yml` or to the pages front-matter (the option should go into the `scholar` section for each). However, I think it should already filter out `abstract` per default, so I wonder if you changed the configuration.

**Comment by matteofrigo** [comment]
Me too I was surprised to see the abstract there by default. 

It still doesn't work. I guess it has something to do with the theme of the website I'm trying to build.

Thanks anyways :)
