### ISSUE TITLE
WARN -- : Lexer: unexpected token `̈' at 9341; brace level 1; mode :entry.

### ISSUE THREAD

**Issue by kristiannordestgaard** [inukshuk/jekyll-scholar#79]
Cheers,

I get the above entry when running jekyll build with jekyll-scholar. Where do I find the unexpected token? Line 9341 of which file?

**Comment by kristiannordestgaard** [comment]
I managed to find the faulty character, via trial and error - turned out to be an "ö" in an entry name.

**Comment by inukshuk** [comment]
For debugging I normally set a breakpoint here: https://github.com/inukshuk/bibtex-ruby/blob/master/lib/bibtex/lexer.rb#L341 -- or go to character 9341 of the input. But we could consider printing the whole line there.

Can you tell me what the offending line was? Is it something that you would expect the Parser to accept or was it genuinely invalid BibTeX?

**Comment by kristiannordestgaard** [comment]
Ah, so it's the character count - of course! It fits perfectly...

This is what the file looked like before I fixed it. I believe it is indeed invalid BibTeX.

@Book{schröder1982de,
  author =       "Horst Schröder",
  title =        "De første tegneserier",
  subtitle =     "Avistegneserier i USA fra 1896-1940",
  publisher =    "Carlsen",
  year =         "1982",
  archive_location = "1981",
  origtitle =    "De första serierna",
  keywords =     "historie",
  ISBN =         "87-562-2148-7",
}

**Comment by inukshuk** [comment]
IIRC the key is indeed supposed to be ASCII only. However, if you like you can configure the parser to accept it, by adjusting the pattern `BibTeX::Lexer.patterns[:key]` -- you could do this, for instance in any file in your _plugins directory.
