### ISSUE TITLE
Sorting the bibliography by author name?

### ISSUE THREAD

**Issue by kristiannordestgaard** [inukshuk/jekyll-scholar#80]
Hello Sylvester,

First of all, **stellar** work! 

The question is, can I sort a bibliography by author name? I see this has been touched upon [here](https://github.com/inukshuk/jekyll-scholar/issues/25) but I would like to know exactly how it's done, if possible. 

Thanks, 
Kristian

**Comment by inukshuk** [comment]
Basically, you can sort by author name by setting the `sort_by` option to `author` in your configuration. This will compare the names as strings in sort order (family name, given name). If you need something more complex, the easiest thing would be to override the [sort method](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L141) and add your custom behaviour there.

**Comment by kristiannordestgaard** [comment]
Ah, but of course! Is there a way to make it sort editors with the authors, instead of by themselves? 

If you'd like to, you can see my project [here](http://kristian.anapnea.net/tegnebib/).

**Comment by inukshuk** [comment]
You can sort by authors and editors by setting your sort key to `author, editor`... however this will not give you the expected result, if, for instance, you have a book with no authors but editors.

To work around this, like I mentioned earlier, you can override the sort method. Or you could override [bibliography method](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L116) -- right after the bibliography is loaded you coul loop through all entries and set a new field 'contributors' which contains all authors and editors combined. Then you set your sort key to `contributors`. Finally, if you don't want to override any Ruby code you could also add this field manually to your bibtex file.

**Comment by kristiannordestgaard** [comment]
Thanks, I'll look into that.
