### ISSUE TITLE
Add --offset filter option to accompany --max

### ISSUE THREAD

**Issue by iiegn** [inukshuk/jekyll-scholar#85]
for a  poor man's paging (or other suitable use-cases) ``--max`` should be accompanied by an ``--offset`` option
so, ``--max 10`` could be followed by ``--offset 11`` on another page.

**Comment by jbreitbart** [comment]
Is this fixed and working with the latest release?

I am looking for a way to show the latest 5 publications and hide the rest behind a "More..." link and that seems a reasonable way to do it.

**Comment by iiegn** [comment]
yes, 7c1651b4c838ad7d60136949a0710662076570d9 landed in 5.0.0 and 5.1.0
