### ISSUE TITLE
Ordered lists

### ISSUE THREAD

**Issue by jonso99** [inukshuk/jekyll-scholar#89]
This is a fantastic addition to jekyll, great work.

I am now integrating it onto several pages and ran into one issue.  My pages use Bootstrap, and I'd like to use that to format the entries.  Easy enough, except the ordered list (and the wrapping in HTML tags).  I guess I could hack it to remove those, but it would be even better if there was an option to not to use ordered lists and tags. 

thanks for creating jekyll-scholar 

jonsi

**Comment by inukshuk** [comment]
There are a couple of options to control this. You can set the the `bibliography_list_tag` (default is 'ol'); if you set it to something other than 'ol' or 'ul' you also need to change `bibliography_item_tag` to something other than 'li'.
