### ISSUE TITLE
Disabling "Details" link?

### ISSUE THREAD

**Issue by kristiannordestgaard** [inukshuk/jekyll-scholar#91]
Hi,

This is likely to just be my less than stellar skills, but ...

I have a file in _layouts called bibtex.html with this front matter: 

    ---
    ---
    {{ reference }}

And thus I get a "Details" link for each entry. The relevant part of my _config.yml is: 

gems: ['jekyll/scholar']

    scholar:
      style: chicago-fullnote-bibliography 
      locale: en

      sort_by: year 
      order: ascending

      source: ./_bibliography
      bibliography: kneale.bib
      bibliography_template: bibtex 

      replace_strings: true
      join_strings:    true

      query: "@*"
    

How do I disable the "Details" link? And by the way, it seems that bibtex.html is called (due to the front matter?) whether it is mentioned in _config.yml or not.

**Comment by kristiannordestgaard** [comment]
Hmm, it seems it could be fixed with renaming bibtex.html to (for instance) bibtex2.html. I take it that the other name was reserved?

**Comment by inukshuk** [comment]
`bibtex.html` is the default for the `details_layout` options; you can set it to some other value in your config file.

Also see https://github.com/inukshuk/jekyll-scholar#detail-pages

**Comment by kristiannordestgaard** [comment]
Thanks for your swift reply, I will close the issue.
