### ISSUE TITLE
How to cite only one specific author?

### ISSUE THREAD

**Issue by kristiannordestgaard** [inukshuk/jekyll-scholar#92]
Hello, 

How do I make this so that co-authored books are omitted? 

    {% bibliography --query @*[author~=Knuth, type=book] %}

Kristian

**Comment by inukshuk** [comment]
I don't think you can do that using only the query string; but it is easy to do in Ruby (untested):

    bibliography.select { |e|
      e.has_type?('book') && e.author.length == 1 && e.author[0].family == 'Knuth'
    }
