### ISSUE TITLE
Feature request: Override configuration in page frontmatter

### ISSUE THREAD

**Issue by davidchisnall** [inukshuk/jekyll-scholar#95]
Currently, the .bib file to use (for example) can only be specified centrally for the site.  If you want to use a different file, then you must add `--file` to every `{% cite %}` and `{% bibliography %}` command, which gets a bit unwieldy.

It would be great if all of the site-wide configuration options could be overridden in the frontmatter, so that a single page could just specify the bibliography (and style and so on) to use in a single place.

**Comment by inukshuk** [comment]
Fully agree. `style` is another option that would make sense to allow to override in the front matter. In fact, it's true for most of our options. I'll gladly merge any PRs if they come with tests.

**Comment by inukshuk** [comment]
Also see #52

**Comment by i2000s** [comment]
@inukshuk Could you point me to where the default options are fetched into the program? I am not familiar with ruby, but I can have a try when I have time to hack. Thanks.

**Comment by inukshuk** [comment]
Most of the functionality of jekyll-scholar is in the [Utilities module](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb) which is included into most of the jekyll tags or converter plugins. Notice it provides a `config` reader which is used to access the configuration; this required `@config` to be set. Using the `bibliography` tag as an illustration, this is how the config is set:

1. In the constructor, the [default settings are copied](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/tags/bibliography.rb#L10)
2. When the tag is rendered [the render context is set](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/tags/bibliography.rb#L16)
3. `set_context` [merges the default configuration with your actual configuration](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L688).

It would probably be enough to check for and merge page specific settings at this point.

There are many tags which allow their own options to override the site-wide settings. For example, you can pass a different style to `bibliography` via the `--style` parameter. This just [stores the style as an instance variable](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L78) and all other utility methods access the style via a reader which simply [returns the 'local' style or the configured styles](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L426). My assumption would probably have to be checked for each parameter, but in general I think it would just work to load the optional settings from the page's front matter when the context is set and merge it into `config`.

**Comment by i2000s** [comment]
Thank you very much for the detailed illustration. I'll take a note for now and may come back for questions :)

**Comment by i2000s** [comment]
I checked your code a little bit on the surface. I am thinking to use `@array = context['page']` to fetch all the front matter variables into one `array` variable and then compare the elements of `array` with the variables in the default set. If the front matter has defined the variable, use the one defined in `array` to replace the one defined in configure file. Do you think this will work?

However, when I dig into the code, I find different variables might have been fetched or merged in different ways (or I have missed something). For example, the example of the `--style` case was merged in [the utilities.rb file](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L426), which I think I can merge the definitions in the `utilities.rb` file with the front matter. But cases like `bibliography_list_attributes` is merged in `tags/bibliography.rb` file on [line 96](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/tags/bibliography.rb#L96) and further used in the [utilities.rb](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L645) for the variable called `content_tag`. For the later case, which motivated me to try, should I merge it in the `utilities.rb` code or anywhere?

**Comment by inukshuk** [comment]
The configuration settings for `bibliography_list_attributes` are not changed or merged [there on line 96](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/tags/bibliography.rb#L96) -- what is being merged there is just the attributes hash passed to the tag (comprising the class and further attributes, if defined); note that `config` does not change there at all.

The `Utilities` module is included into each of the jekyll plugins; for example the `bibliography` tag [includes it here](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/tags/bibliography.rb#L5). Jekyll-Scholar is a collection of Jekyll plugins which share a lot of functionality (e.g., access your references, render them, etc.) so most of the functionality lives in `Utilities` and is included into every tag, converter, or generator plugin -- the utilities module's purpose is where the shared code lives. I would think that overriding settings in the front matter is something from which all plugins can benefit and ideally it would be implemented completely in `Utilities` (for the individual plugins, nothing much changes: they just access settings in `config` and are not concerned whether a particular setting was defined by the defaults, the site or page configuration, or a tag parameter.

**Comment by inukshuk** [comment]
Regarding the settings themselves: we should group all settings in the front matter under `scholar`, like we do in the main config file. This would greatly simplify the implementation, because you can just fetch the `scholar` hash from the page's front matter (if it exists) and merge it into `config`. This needs to happen before parameters are parsed (e.g. in `set_context` probably).
