### ISSUE TITLE
add .bib file as dependency for pages where bibliography tag is used (Jekyll 3)

### ISSUE THREAD

**Issue by mamoll** [inukshuk/jekyll-scholar#96]
Jekyll 3 uses dependency tracking to speed up incremental builds. Jekyll-scholar doesn't seem to support that. Whenever a page uses the bibliography tag, a dependency on the .bib file used should be added. My Ruby knowledge is rather limited, so I don't know how to get the .bib file name in the render() method. 

Here is how dependencies are handled for the include tag's render method in jekyll 3:
```
        # Add include to dependency tree
        if context.registers[:page] and context.registers[:page].has_key? "path"
          site.regenerator.add_dependency(
            site.in_source_dir(context.registers[:page]["path"]),
            path
          )
        end
```

**Comment by inukshuk** [comment]
This sounds great.

We have a few helper methods in the utilities module that you can consult to get the bib files, e.g. [bibtex_paths](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L106) for the absolute paths or [bibtex_files](https://github.com/inukshuk/jekyll-scholar/blob/master/lib/jekyll/scholar/utilities.rb#L88) for the file names.
