### ISSUE TITLE
error loading jekyll-scholar when using bundler gem

### ISSUE THREAD

**Issue by timjore** [inukshuk/jekyll-scholar#97]
I am attempting to install jekyll-scholar with a theme that uses the `bundler` gem. I have added it to the config.yml:

```
gems: 
  - jekyll-scholar
  - jekyll-sitemap
```

and also to the Gemfile:

```
gem 'jekyll'
gem 'jekyll-scholar'
gem 'jekyll-sitemap'
gem 'octopress', '~> 3.0.0.rc.12'
gem 'rouge'
```

then run `bundle install` which shows:

```
...
Using jekyll 2.5.3
Using jekyll-scholar 4.5.0
Using jekyll-sitemap 0.8.0
...
```

but still receive errors when serving the site:

```
$ bundle exec jekyll serve
Configuration file: /Users/tim/src/site/_config.yml
/Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jekyll-scholar (LoadError)
...
```

I have `citeproc-ruby` and `bibtex-ruby` installed. Do I have something misconfigured or is the bundler not picking up something?

**Comment by inukshuk** [comment]
Hi @timjore, you need to distinguish between the gem name `jekyll-scholar` and the file to require `jekyll/scholar` (conventional for Ruby Gems). Therefore, in your `_config.yml` use `jekyll/scholar` and it should work.
