### ISSUE TITLE
"Author (year)" citation format?

### ISSUE THREAD

**Issue by feilong** [inukshuk/jekyll-scholar#99]
Hi,

I'm not sure if this option is available for citations, but I think it would be helpful to have this "author (year)" option.

I hope this won't be difficult considering the `--suppress_author` option is already available.

**Comment by inukshuk** [comment]
Do you mean the citation style? You can use any CSL style, there is probably one available using an 'author (year)' style -- and if there isn't you could just edit one of the existing styles.

**Comment by feilong** [comment]
I think they're different. I use the default APA style all the time. What I want is using both "(author, year)" and "author (year)" in the same file, and I was wondering if there's an option that can switch from the default "(author, year)" to "author (year)" for some citations.

**Comment by inukshuk** [comment]
I see. You're right, that's what `--suppress_author` is for; so you would spell out the author yourself and the style would generate just the year in parentheses.

**Comment by feilong** [comment]
Yes, `--suppress_author` could do the work.
I'm just too lazy to type the author names, and sometimes I misspell them. Therefore I hope for another option that can save me from the typing.
